INSERT INTO `character_versions` (id,character_id,name,short_name,aliases,description,era,arc,sort_order,canonical,source_endpoint,parent_version_id,created) VALUES
 ('madara-edo-tensei','madara','Edo Tensei Madara','Edo Tensei','["Reanimated Madara","Edo Madara"]','Madara in his reanimated Fourth Shinobi World War combat state.','Naruto Shippuden','Fourth Shinobi World War',10,1,'Naruto Shippuden · Fourth Shinobi World War',NULL,1791398520000),
 ('madara-revived','madara','Revived Madara','Revived','["Alive Madara","Revived Uchiha Madara"]','Madara after returning to a living body during the Fourth Shinobi World War.','Naruto Shippuden','Fourth Shinobi World War',20,1,'Naruto Shippuden · Fourth Shinobi World War','madara-edo-tensei',1791398520000),
 ('madara-ten-tails-jinchuriki','madara','Ten-Tails Jinchuriki Madara','Ten-Tails Jinchuriki','["Juubi Madara","Six Paths Madara","Ten Tails Madara"]','Madara in his Ten-Tails jinchuriki Six Paths-era combat state.','Naruto Shippuden','Fourth Shinobi World War',30,1,'Naruto Shippuden · Fourth Shinobi World War','madara-revived',1791398520000),
 ('gojo-hidden-inventory-awakened','gojo','Awakened Hidden Inventory Gojo','Awakened','["Awakened Gojo","Teen Gojo"]','Gojo after his awakening during the Hidden Inventory period.','Jujutsu Kaisen','Hidden Inventory',10,1,'Jujutsu Kaisen · Hidden Inventory',NULL,1791398520000),
 ('gojo-shibuya','gojo','Shibuya Incident Gojo','Shibuya','["Shibuya Gojo","Adult Gojo"]','Gojo at the Shibuya Incident anime endpoint.','Jujutsu Kaisen','Shibuya Incident',20,1,'Jujutsu Kaisen · Shibuya Incident','gojo-hidden-inventory-awakened',1791398520000),
 ('gojo-shinjuku','gojo','Shinjuku Showdown Gojo','Shinjuku','["Shinjuku Gojo"]','Gojo at his Shinjuku Showdown manga combat endpoint.','Jujutsu Kaisen','Shinjuku Showdown',30,1,'Jujutsu Kaisen manga · Shinjuku Showdown','gojo-shibuya',1791398520000),
 ('itachi-akatsuki','itachi','Akatsuki Itachi','Akatsuki','["Living Itachi","Akatsuki-era Itachi"]','Itachi during his Akatsuki-era combat profile.','Naruto Shippuden',NULL,10,1,'Naruto Shippuden · Akatsuki era',NULL,1791398520000),
 ('itachi-edo-tensei','itachi','Edo Tensei Itachi','Edo Tensei','["Reanimated Itachi","Edo Itachi"]','Itachi in his reanimated Fourth Shinobi World War combat state.','Naruto Shippuden','Fourth Shinobi World War',20,1,'Naruto Shippuden · Fourth Shinobi World War','itachi-akatsuki',1791398520000),
 ('aizen-soul-society','aizen','Soul Society Aizen','Soul Society','["Captain Aizen"]','Aizen at the Soul Society conflict endpoint before later Hogyoku transformations.','Bleach','Soul Society',10,1,'Bleach · Soul Society arc',NULL,1791398520000),
 ('aizen-hogyoku','aizen','Hogyoku Aizen','Hogyoku','["Hōgyoku Aizen","Transcendent Aizen"]','Aizen during his Hogyoku-evolved combat state.','Bleach','Arrancar / Fake Karakura Town',20,1,'Bleach · Arrancar conflict','aizen-soul-society',1791398520000),
 ('aizen-tybw','aizen','Thousand-Year Blood War Aizen','TYBW','["TYBW Aizen","Muken Aizen"]','Aizen at the Thousand-Year Blood War anime endpoint.','Bleach: Thousand-Year Blood War',NULL,30,1,'Bleach: Thousand-Year Blood War anime','aizen-hogyoku',1791398520000),
 ('saitama-hero-association','saitama','Hero Association Saitama','Hero Association','["Caped Baldy","Saitama"]','Saitama at the current anime Hero Association combat endpoint.','One-Punch Man',NULL,10,1,'One-Punch Man anime',NULL,1791398520000),
 ('megumi-season-1','megumi','Season 1 Megumi','Season 1','["Season 1"]','Megumi at the first-season anime combat endpoint.','Jujutsu Kaisen',NULL,10,1,'Jujutsu Kaisen anime season 1',NULL,1791398520000),
 ('megumi-shibuya','megumi','Shibuya Incident Megumi','Shibuya','["Shibuya Megumi"]','Megumi at the Shibuya Incident anime endpoint.','Jujutsu Kaisen','Shibuya Incident',20,1,'Jujutsu Kaisen · Shibuya Incident','megumi-season-1',1791398520000);
--> statement-breakpoint
INSERT INTO `abilities` (id,character_id,name,description,category,created) VALUES
 ('madara-ocular','madara','Sharingan and Rinnegan','Ocular techniques associated with Madara combat profiles.','sensory',1791398520000),
 ('madara-susanoo','madara','Susanoo','Uchiha chakra avatar used for offense and defense.','defensive',1791398520000),
 ('madara-limbo','madara','Limbo','Six Paths-era parallel shadow technique.','hax',1791398520000),
 ('madara-ten-tails','madara','Ten-Tails Jinchuriki','Ten-Tails jinchuriki transformation state.','transformation',1791398520000),
 ('gojo-limitless','gojo','Limitless','Spatial cursed technique used for Infinity, Blue, Red, and Hollow Purple applications.','hax',1791398520000),
 ('gojo-six-eyes','gojo','Six Eyes','Exceptional cursed-energy perception and efficiency.','sensory',1791398520000),
 ('gojo-unlimited-void','gojo','Unlimited Void','Gojo domain expansion.','hax',1791398520000),
 ('gojo-rct','gojo','Reverse Cursed Technique','Reverse cursed energy used for recovery and technique support.','technique',1791398520000),
 ('itachi-genjutsu','itachi','Sharingan Genjutsu','Sharingan-based illusion techniques including high-level genjutsu.','hax',1791398520000),
 ('itachi-amaterasu','itachi','Amaterasu','Mangekyo Sharingan black-flame technique.','technique',1791398520000),
 ('itachi-susanoo','itachi','Susanoo','Itachi defensive and offensive chakra avatar.','defensive',1791398520000),
 ('aizen-kyoka-suigetsu','aizen','Kyoka Suigetsu','Complete hypnosis through Aizen zanpakuto ability.','hax',1791398520000),
 ('aizen-kido','aizen','Kido','High-level Soul Reaper spell techniques.','technique',1791398520000),
 ('aizen-hogyoku-ability','aizen','Hogyoku Evolution','Hogyoku-driven transformation and adaptation state.','transformation',1791398520000),
 ('saitama-physical','saitama','Overwhelming Physical Ability','Extreme strength, speed, durability, and close-range combat.','physical',1791398520000),
 ('saitama-serious-punch','saitama','Serious Punch','A named high-output punch from Saitama serious-series attacks.','technique',1791398520000),
 ('megumi-ten-shadows','megumi','Ten Shadows Technique','Shikigami-based inherited cursed technique.','summoning',1791398520000),
 ('megumi-chimera-shadow-garden','megumi','Chimera Shadow Garden','Megumi incomplete domain expansion.','hax',1791398520000);
--> statement-breakpoint
INSERT INTO `version_abilities` (version_id,ability_id,status,notes) VALUES
 ('madara-edo-tensei','madara-ocular','available',''),
 ('madara-edo-tensei','madara-susanoo','available',''),
 ('madara-revived','madara-ocular','available',''),
 ('madara-revived','madara-susanoo','available',''),
 ('madara-ten-tails-jinchuriki','madara-ocular','available',''),
 ('madara-ten-tails-jinchuriki','madara-susanoo','available',''),
 ('madara-ten-tails-jinchuriki','madara-limbo','available',''),
 ('madara-ten-tails-jinchuriki','madara-ten-tails','mastered',''),
 ('gojo-hidden-inventory-awakened','gojo-limitless','mastered',''),
 ('gojo-hidden-inventory-awakened','gojo-six-eyes','available',''),
 ('gojo-hidden-inventory-awakened','gojo-rct','available',''),
 ('gojo-shibuya','gojo-limitless','mastered',''),
 ('gojo-shibuya','gojo-six-eyes','available',''),
 ('gojo-shibuya','gojo-rct','available',''),
 ('gojo-shibuya','gojo-unlimited-void','mastered',''),
 ('gojo-shinjuku','gojo-limitless','mastered',''),
 ('gojo-shinjuku','gojo-six-eyes','available',''),
 ('gojo-shinjuku','gojo-rct','available',''),
 ('gojo-shinjuku','gojo-unlimited-void','mastered',''),
 ('itachi-akatsuki','itachi-genjutsu','mastered',''),
 ('itachi-akatsuki','itachi-amaterasu','available',''),
 ('itachi-akatsuki','itachi-susanoo','available',''),
 ('itachi-edo-tensei','itachi-genjutsu','mastered',''),
 ('itachi-edo-tensei','itachi-amaterasu','available',''),
 ('itachi-edo-tensei','itachi-susanoo','available',''),
 ('aizen-soul-society','aizen-kyoka-suigetsu','mastered',''),
 ('aizen-soul-society','aizen-kido','available',''),
 ('aizen-hogyoku','aizen-kyoka-suigetsu','mastered',''),
 ('aizen-hogyoku','aizen-kido','available',''),
 ('aizen-hogyoku','aizen-hogyoku-ability','available',''),
 ('aizen-tybw','aizen-kyoka-suigetsu','mastered',''),
 ('aizen-tybw','aizen-kido','available',''),
 ('aizen-tybw','aizen-hogyoku-ability','available',''),
 ('saitama-hero-association','saitama-physical','mastered',''),
 ('saitama-hero-association','saitama-serious-punch','available',''),
 ('megumi-season-1','megumi-ten-shadows','available',''),
 ('megumi-shibuya','megumi-ten-shadows','available',''),
 ('megumi-shibuya','megumi-chimera-shadow-garden','limited','');
--> statement-breakpoint
INSERT INTO `squad_version_costs` (`version_id`,`character_id`,`cost`,`updated`) VALUES
 ('madara-edo-tensei','madara',78,1791398520000),
 ('madara-revived','madara',86,1791398520000),
 ('madara-ten-tails-jinchuriki','madara',98,1791398520000),
 ('gojo-hidden-inventory-awakened','gojo',34,1791398520000),
 ('gojo-shibuya','gojo',38,1791398520000),
 ('gojo-shinjuku','gojo',44,1791398520000),
 ('itachi-akatsuki','itachi',30,1791398520000),
 ('itachi-edo-tensei','itachi',37,1791398520000),
 ('aizen-soul-society','aizen',55,1791398520000),
 ('aizen-hogyoku','aizen',75,1791398520000),
 ('aizen-tybw','aizen',82,1791398520000),
 ('saitama-hero-association','saitama',95,1791398520000),
 ('megumi-season-1','megumi',8,1791398520000),
 ('megumi-shibuya','megumi',12,1791398520000);
