-- Append-only tactical metadata. Existing submissions/squads retain original IDs and snapshots.
CREATE TABLE `version_combat_roles` (
 `version_id` text NOT NULL REFERENCES `character_versions`(`id`) ON DELETE CASCADE,
 `role` text NOT NULL CHECK (`role` IN ('dps','tank','support','healer','controller','strategist','assassin','speedster','summoner','reality_manipulator','defense')),
 `priority` text NOT NULL CHECK (`priority` IN ('primary','secondary')),
 `notes` text NOT NULL DEFAULT '',
 PRIMARY KEY (`version_id`,`role`)
);
--> statement-breakpoint
CREATE INDEX `idx_version_combat_roles_role` ON `version_combat_roles` (`role`,`version_id`);
--> statement-breakpoint
CREATE TABLE `version_strategic_traits` (
 `version_id` text NOT NULL REFERENCES `character_versions`(`id`) ON DELETE CASCADE,
 `trait` text NOT NULL CHECK (`trait` IN ('healing','barrier','crowd_control','mobility','teleportation','information','buff','debuff','sealing','summoning','illusion','stealth','long_range','close_range','area_damage','single_target','adaptation','prediction','anti_regeneration')),
 PRIMARY KEY (`version_id`,`trait`)
);
--> statement-breakpoint
CREATE INDEX `idx_version_strategic_traits_trait` ON `version_strategic_traits` (`trait`,`version_id`);
--> statement-breakpoint
ALTER TABLE `squad_submission_members` ADD COLUMN `roles_snapshot` text;
--> statement-breakpoint
ALTER TABLE `squad_submission_members` ADD COLUMN `traits_snapshot` text;
--> statement-breakpoint
INSERT INTO `version_combat_roles` (`version_id`,`role`,`priority`,`notes`) VALUES
 ('naruto-chunin-exam','dps','primary',''),
 ('naruto-chunin-exam','summoner','primary',''),
 ('naruto-six-paths','dps','primary',''),
 ('naruto-six-paths','support','primary',''),
 ('naruto-six-paths','speedster','secondary',''),
 ('naruto-six-paths','controller','secondary',''),
 ('goku-saiyan-saga','dps','primary',''),
 ('goku-mastered-ultra-instinct','dps','primary',''),
 ('goku-mastered-ultra-instinct','speedster','primary',''),
 ('gojo-hidden-inventory-awakened','defense','primary',''),
 ('gojo-hidden-inventory-awakened','dps','primary',''),
 ('gojo-shibuya','defense','primary',''),
 ('gojo-shibuya','controller','primary',''),
 ('gojo-shibuya','dps','secondary',''),
 ('gojo-shinjuku','defense','primary',''),
 ('gojo-shinjuku','controller','primary',''),
 ('gojo-shinjuku','dps','secondary',''),
 ('aizen-soul-society','controller','primary',''),
 ('aizen-soul-society','strategist','primary',''),
 ('aizen-hogyoku','controller','primary',''),
 ('aizen-hogyoku','strategist','primary',''),
 ('aizen-hogyoku','dps','secondary',''),
 ('aizen-tybw','controller','primary',''),
 ('aizen-tybw','strategist','primary',''),
 ('itachi-akatsuki','controller','primary',''),
 ('itachi-akatsuki','strategist','primary',''),
 ('itachi-akatsuki','assassin','secondary',''),
 ('itachi-edo-tensei','controller','primary',''),
 ('itachi-edo-tensei','strategist','primary',''),
 ('itachi-edo-tensei','assassin','secondary',''),
 ('levi-season-1','assassin','primary',''),
 ('levi-season-1','speedster','primary',''),
 ('levi-thunder-spears','assassin','primary',''),
 ('levi-thunder-spears','speedster','primary',''),
 ('levi-thunder-spears','dps','secondary',''),
 ('sakura-byakugo','healer','primary',''),
 ('sakura-byakugo','dps','primary',''),
 ('sakura-byakugo','tank','secondary',''),
 ('chopper-brain-point','healer','primary',''),
 ('chopper-brain-point','support','primary',''),
 ('chopper-guard-point','tank','primary',''),
 ('chopper-guard-point','support','primary',''),
 ('chopper-monster-point','tank','primary',''),
 ('chopper-monster-point','dps','primary',''),
 ('shikamaru-standard','strategist','primary',''),
 ('shikamaru-standard','controller','primary',''),
 ('megumi-season-1','summoner','primary',''),
 ('megumi-season-1','strategist','primary',''),
 ('megumi-shibuya','summoner','primary',''),
 ('megumi-shibuya','controller','primary',''),
 ('megumi-shibuya','strategist','secondary',''),
 ('madara-edo-tensei','controller','primary',''),
 ('madara-edo-tensei','dps','primary',''),
 ('madara-edo-tensei','tank','secondary',''),
 ('madara-ten-tails-jinchuriki','controller','primary',''),
 ('madara-ten-tails-jinchuriki','dps','primary',''),
 ('madara-ten-tails-jinchuriki','tank','secondary',''),
 ('senku-science-kingdom','strategist','primary',''),
 ('senku-science-kingdom','support','primary',''),
 ('asta-devil-union','dps','primary',''),
 ('asta-devil-union','assassin','primary',''),
 ('usopp-pop-greens','support','primary',''),
 ('usopp-pop-greens','controller','primary',''),
 ('rukia-bankai','dps','primary',''),
 ('rukia-bankai','controller','primary',''),
 ('mikasa-thunder-spears','assassin','primary',''),
 ('mikasa-thunder-spears','speedster','primary',''),
 ('saitama-hero-association','dps','primary',''),
 ('saitama-hero-association','tank','primary',''),
 ('shinra-rapid','dps','primary',''),
 ('shinra-rapid','speedster','primary','');
--> statement-breakpoint
INSERT INTO `version_strategic_traits` (`version_id`,`trait`) VALUES
 ('naruto-chunin-exam','summoning'),
 ('naruto-chunin-exam','close_range'),
 ('naruto-six-paths','summoning'),
 ('naruto-six-paths','mobility'),
 ('naruto-six-paths','area_damage'),
 ('naruto-six-paths','long_range'),
 ('goku-saiyan-saga','close_range'),
 ('goku-saiyan-saga','long_range'),
 ('goku-mastered-ultra-instinct','mobility'),
 ('goku-mastered-ultra-instinct','close_range'),
 ('goku-mastered-ultra-instinct','single_target'),
 ('gojo-hidden-inventory-awakened','barrier'),
 ('gojo-hidden-inventory-awakened','mobility'),
 ('gojo-hidden-inventory-awakened','long_range'),
 ('gojo-shibuya','barrier'),
 ('gojo-shibuya','crowd_control'),
 ('gojo-shibuya','area_damage'),
 ('gojo-shinjuku','barrier'),
 ('gojo-shinjuku','crowd_control'),
 ('gojo-shinjuku','area_damage'),
 ('aizen-soul-society','illusion'),
 ('aizen-soul-society','information'),
 ('aizen-hogyoku','illusion'),
 ('aizen-hogyoku','adaptation'),
 ('aizen-hogyoku','long_range'),
 ('aizen-tybw','illusion'),
 ('aizen-tybw','information'),
 ('aizen-tybw','long_range'),
 ('itachi-akatsuki','illusion'),
 ('itachi-akatsuki','single_target'),
 ('itachi-akatsuki','sealing'),
 ('itachi-edo-tensei','illusion'),
 ('itachi-edo-tensei','single_target'),
 ('itachi-edo-tensei','sealing'),
 ('levi-season-1','mobility'),
 ('levi-season-1','close_range'),
 ('levi-season-1','single_target'),
 ('levi-thunder-spears','mobility'),
 ('levi-thunder-spears','single_target'),
 ('sakura-byakugo','healing'),
 ('sakura-byakugo','close_range'),
 ('chopper-brain-point','healing'),
 ('chopper-brain-point','information'),
 ('chopper-guard-point','close_range'),
 ('chopper-monster-point','close_range'),
 ('shikamaru-standard','crowd_control'),
 ('shikamaru-standard','information'),
 ('megumi-season-1','summoning'),
 ('megumi-season-1','single_target'),
 ('megumi-shibuya','summoning'),
 ('megumi-shibuya','crowd_control'),
 ('madara-edo-tensei','area_damage'),
 ('madara-edo-tensei','long_range'),
 ('madara-ten-tails-jinchuriki','area_damage'),
 ('madara-ten-tails-jinchuriki','long_range'),
 ('senku-science-kingdom','information'),
 ('senku-science-kingdom','prediction'),
 ('asta-devil-union','close_range'),
 ('asta-devil-union','mobility'),
 ('usopp-pop-greens','long_range'),
 ('usopp-pop-greens','crowd_control'),
 ('rukia-bankai','area_damage'),
 ('rukia-bankai','crowd_control'),
 ('mikasa-thunder-spears','mobility'),
 ('mikasa-thunder-spears','single_target'),
 ('saitama-hero-association','close_range'),
 ('saitama-hero-association','single_target'),
 ('shinra-rapid','mobility'),
 ('shinra-rapid','close_range');
