-- Append-only legacy SQLite catalog expansion. PostgreSQL uses packages/database/seeds/catalog.jsonl.
-- Keep existing historic character IDs and submitted squad snapshots unchanged.
INSERT OR IGNORE INTO `character_versions` (`id`,`character_id`,`name`,`short_name`,`aliases`,`description`,`era`,`arc`,`sort_order`,`canonical`,`source_endpoint`,`parent_version_id`,`created`) VALUES
 ('vegeta-saiyan-saga','vegeta','Saiyan Saga Vegeta','Saiyan Saga','["Saiyan Prince"]','Vegeta during his early confrontation with Earth defenders.','Dragon Ball Z','Saiyan Saga',10,1,'Dragon Ball Z · Saiyan Saga',NULL,1791504000000),
 ('vegeta-super-saiyan-blue','vegeta','Super Saiyan Blue Vegeta','SSB','["Super Saiyan Blue","SSB Vegeta"]','Vegeta with Super Saiyan Blue as shown in Dragon Ball Super.','Dragon Ball Super',NULL,20,1,'Dragon Ball Super','vegeta-saiyan-saga',1791504000000),
 ('sasuke-hebi','sasuke','Hebi Sasuke','Hebi','["Hebi","Post-timeskip"]','Sasuke during the Hebi period with Chidori and Sharingan.','Naruto Shippuden','Hebi',10,1,'Naruto Shippuden · Hebi',NULL,1791504000000),
 ('sasuke-rinnegan','sasuke','Rinnegan Sasuke','Rinnegan','["Six Paths Sasuke","War Arc Sasuke"]','Sasuke after receiving the Rinnegan in the Fourth Shinobi World War.','Naruto Shippuden','Fourth Shinobi World War',20,1,'Naruto Shippuden · Fourth Shinobi World War','sasuke-hebi',1791504000000),
 ('kakashi-sharingan','kakashi','Sharingan Kakashi','Sharingan','["Copy Ninja Kakashi"]','Kakashi with Sharingan combat and Raikiri.','Naruto','Original series',10,1,'Naruto · Original series',NULL,1791504000000),
 ('kakashi-war-arc','kakashi','War Arc Kakashi','War Arc','["Kamui Kakashi"]','Kakashi using Kamui during the Fourth Shinobi World War.','Naruto Shippuden','Fourth Shinobi World War',20,1,'Naruto Shippuden · Fourth Shinobi World War','kakashi-sharingan',1791504000000),
 ('zoro-enies-lobby','zoro','Enies Lobby Zoro','Enies Lobby','["Asura Zoro"]','Zoro with three-sword style during Enies Lobby.','One Piece','Enies Lobby',10,1,'One Piece · Enies Lobby',NULL,1791504000000),
 ('zoro-wano','zoro','Wano Zoro','Wano','["King of Hell Zoro","Enma Zoro"]','Zoro with Wano-era sword techniques and Haki.','One Piece','Wano Country',20,1,'One Piece · Wano Country','zoro-enies-lobby',1791504000000),
 ('sanji-enies-lobby','sanji','Enies Lobby Sanji','Enies Lobby','["Diable Jambe Sanji"]','Sanji during Enies Lobby with Diable Jambe.','One Piece','Enies Lobby',10,1,'One Piece · Enies Lobby',NULL,1791504000000),
 ('sanji-wano','sanji','Wano Sanji','Wano','["Ifrit Jambe Sanji"]','Sanji using Ifrit Jambe during Wano.','One Piece','Wano Country',20,1,'One Piece · Wano Country','sanji-enies-lobby',1791504000000),
 ('sukuna-vessel','sukuna','Early Vessel Sukuna','Vessel','["Yuji Vessel","Early Sukuna"]','Sukuna manifesting through Yuji''s body during early anime arcs.','Jujutsu Kaisen','Season 1',10,1,'Jujutsu Kaisen · Season 1',NULL,1791504000000),
 ('sukuna-shibuya','sukuna','Shibuya Sukuna','Shibuya','["Malevolent Shrine Sukuna"]','Sukuna during the Shibuya Incident anime arc.','Jujutsu Kaisen','Shibuya Incident',20,1,'Jujutsu Kaisen · Shibuya Incident','sukuna-vessel',1791504000000),
 ('yuta-jujutsu-zero','yuta','Jujutsu Kaisen 0 Yuta','JJK 0','["Jujutsu Kaisen Zero","Yuta Okkotsu Film"]','Yuta at the end of the Jujutsu Kaisen 0 film.','Jujutsu Kaisen 0','JJK 0',10,1,'Jujutsu Kaisen 0 · JJK 0',NULL,1791504000000),
 ('yuta-culling-game','yuta','Culling Game Yuta','Culling Game','["Sendai Colony Yuta","Manga Yuta"]','Yuta during the Culling Game manga arc; manga spoilers.','Jujutsu Kaisen manga','Culling Game',20,1,'Jujutsu Kaisen manga · Culling Game','yuta-jujutsu-zero',1791504000000),
 ('nezuko-season-1','nezuko','Season 1 Nezuko','Season 1','["Early Nezuko"]','Nezuko''s initial demon combat profile.','Demon Slayer','Season 1',10,1,'Demon Slayer · Season 1',NULL,1791504000000),
 ('nezuko-entertainment-district','nezuko','Entertainment District Nezuko','Entertainment District','["Exploding Blood Nezuko"]','Nezuko during the Entertainment District anime arc.','Demon Slayer','Entertainment District',20,1,'Demon Slayer · Entertainment District','nezuko-season-1',1791504000000);

INSERT OR IGNORE INTO `abilities` (`id`,`character_id`,`name`,`description`,`category`,`created`) VALUES
 ('vegeta-ki','vegeta','Saiyan Ki Combat','Ki blasts and martial arts with Saiyan combat strength.','energy',1791504000000),
 ('vegeta-galick-gun','vegeta','Galick Gun','Directed ki-beam attack.','technique',1791504000000),
 ('vegeta-blue','vegeta','Super Saiyan Blue','God-ki Super Saiyan transformation.','transformation',1791504000000),
 ('sasuke-chidori','sasuke','Chidori','Lightning nature transformation concentrated in a close-range thrust.','technique',1791504000000),
 ('sasuke-sharingan','sasuke','Sharingan','Uchiha visual perception and genjutsu.','sensory',1791504000000),
 ('sasuke-rinnegan-ability','sasuke','Rinnegan','Six Paths ocular techniques including space-time substitution.','hax',1791504000000),
 ('kakashi-raikiri','kakashi','Raikiri','Lightning Blade, a precision lightning attack.','technique',1791504000000),
 ('kakashi-sharingan','kakashi','Sharingan','Copy-ninja ocular tracking and combat analysis.','sensory',1791504000000),
 ('kakashi-kamui','kakashi','Kamui','Mangekyo Sharingan space-time technique.','hax',1791504000000),
 ('zoro-three-sword','zoro','Three-Sword Style','Santoryu swordsmanship using three blades.','weapon',1791504000000),
 ('zoro-armament','zoro','Armament Haki','Haki reinforcement for attacks and defense.','energy',1791504000000),
 ('zoro-king-of-hell','zoro','King of Hell Style','Advanced sword techniques associated with Enma and Haki.','technique',1791504000000),
 ('sanji-black-leg','sanji','Black Leg Style','High-speed kicking-based martial arts.','physical',1791504000000),
 ('sanji-diable-jambe','sanji','Diable Jambe','Flame-enhanced kicks.','technique',1791504000000),
 ('sanji-ifrit-jambe','sanji','Ifrit Jambe','Advanced hotter flame-enhanced kicks.','technique',1791504000000),
 ('sukuna-slashes','sukuna','Cleave and Dismantle','Sukuna''s slashing cursed techniques.','technique',1791504000000),
 ('sukuna-rct','sukuna','Reverse Cursed Technique','Cursed-energy-based regeneration.','defensive',1791504000000),
 ('sukuna-domain','sukuna','Malevolent Shrine','Open-barrier domain expansion.','hax',1791504000000),
 ('yuta-sword','yuta','Cursed Energy Swordplay','Katana fighting reinforced with cursed energy.','weapon',1791504000000),
 ('yuta-rika','yuta','Rika','Rika manifestation used for support and combat.','summoning',1791504000000),
 ('yuta-copy','yuta','Copy','Conditional use of copied cursed techniques.','hax',1791504000000),
 ('nezuko-regeneration','nezuko','Demon Regeneration','Rapid healing as a demon.','defensive',1791504000000),
 ('nezuko-kicks','nezuko','Close-Range Kicks','Powerful close-range physical combat.','physical',1791504000000),
 ('nezuko-exploding-blood','nezuko','Exploding Blood','Nezuko''s burning Blood Demon Art.','technique',1791504000000);

INSERT OR IGNORE INTO `version_abilities` (`version_id`,`ability_id`,`status`,`notes`) VALUES
 ('vegeta-saiyan-saga','vegeta-ki','available',''),
 ('vegeta-saiyan-saga','vegeta-galick-gun','available',''),
 ('vegeta-super-saiyan-blue','vegeta-ki','available',''),
 ('vegeta-super-saiyan-blue','vegeta-galick-gun','available',''),
 ('vegeta-super-saiyan-blue','vegeta-blue','available',''),
 ('sasuke-hebi','sasuke-chidori','available',''),
 ('sasuke-hebi','sasuke-sharingan','available',''),
 ('sasuke-rinnegan','sasuke-chidori','available',''),
 ('sasuke-rinnegan','sasuke-sharingan','available',''),
 ('sasuke-rinnegan','sasuke-rinnegan-ability','available',''),
 ('kakashi-sharingan','kakashi-raikiri','available',''),
 ('kakashi-sharingan','kakashi-sharingan','available',''),
 ('kakashi-war-arc','kakashi-raikiri','available',''),
 ('kakashi-war-arc','kakashi-sharingan','available',''),
 ('kakashi-war-arc','kakashi-kamui','available',''),
 ('zoro-enies-lobby','zoro-three-sword','available',''),
 ('zoro-wano','zoro-three-sword','available',''),
 ('zoro-wano','zoro-armament','available',''),
 ('zoro-wano','zoro-king-of-hell','available',''),
 ('sanji-enies-lobby','sanji-black-leg','available',''),
 ('sanji-enies-lobby','sanji-diable-jambe','available',''),
 ('sanji-wano','sanji-black-leg','available',''),
 ('sanji-wano','sanji-diable-jambe','available',''),
 ('sanji-wano','sanji-ifrit-jambe','available',''),
 ('sukuna-vessel','sukuna-slashes','available',''),
 ('sukuna-vessel','sukuna-rct','available',''),
 ('sukuna-shibuya','sukuna-slashes','available',''),
 ('sukuna-shibuya','sukuna-rct','available',''),
 ('sukuna-shibuya','sukuna-domain','available',''),
 ('yuta-jujutsu-zero','yuta-sword','available',''),
 ('yuta-jujutsu-zero','yuta-rika','available',''),
 ('yuta-culling-game','yuta-sword','available',''),
 ('yuta-culling-game','yuta-rika','available',''),
 ('yuta-culling-game','yuta-copy','available',''),
 ('nezuko-season-1','nezuko-regeneration','available',''),
 ('nezuko-season-1','nezuko-kicks','available',''),
 ('nezuko-entertainment-district','nezuko-regeneration','available',''),
 ('nezuko-entertainment-district','nezuko-kicks','available',''),
 ('nezuko-entertainment-district','nezuko-exploding-blood','available','');

INSERT OR IGNORE INTO `squad_version_costs` (`version_id`,`character_id`,`cost`,`updated`) VALUES
 ('vegeta-saiyan-saga','vegeta',44,1791504000000),
 ('vegeta-super-saiyan-blue','vegeta',88,1791504000000),
 ('sasuke-hebi','sasuke',48,1791504000000),
 ('sasuke-rinnegan','sasuke',89,1791504000000),
 ('kakashi-sharingan','kakashi',40,1791504000000),
 ('kakashi-war-arc','kakashi',72,1791504000000),
 ('zoro-enies-lobby','zoro',35,1791504000000),
 ('zoro-wano','zoro',70,1791504000000),
 ('sanji-enies-lobby','sanji',33,1791504000000),
 ('sanji-wano','sanji',66,1791504000000),
 ('sukuna-vessel','sukuna',68,1791504000000),
 ('sukuna-shibuya','sukuna',97,1791504000000),
 ('yuta-jujutsu-zero','yuta',56,1791504000000),
 ('yuta-culling-game','yuta',82,1791504000000),
 ('nezuko-season-1','nezuko',25,1791504000000),
 ('nezuko-entertainment-district','nezuko',52,1791504000000);

INSERT OR IGNORE INTO `version_combat_roles` (`version_id`,`role`,`priority`,`notes`) VALUES
 ('vegeta-saiyan-saga','dps','primary',''),
 ('vegeta-saiyan-saga','tank','secondary',''),
 ('vegeta-super-saiyan-blue','dps','primary',''),
 ('vegeta-super-saiyan-blue','speedster','secondary',''),
 ('sasuke-hebi','assassin','primary',''),
 ('sasuke-hebi','strategist','secondary',''),
 ('sasuke-rinnegan','controller','primary',''),
 ('sasuke-rinnegan','dps','secondary',''),
 ('kakashi-sharingan','strategist','primary',''),
 ('kakashi-sharingan','assassin','secondary',''),
 ('kakashi-war-arc','strategist','primary',''),
 ('kakashi-war-arc','controller','secondary',''),
 ('zoro-enies-lobby','dps','primary',''),
 ('zoro-enies-lobby','assassin','secondary',''),
 ('zoro-wano','dps','primary',''),
 ('zoro-wano','tank','secondary',''),
 ('sanji-enies-lobby','speedster','primary',''),
 ('sanji-enies-lobby','dps','secondary',''),
 ('sanji-wano','speedster','primary',''),
 ('sanji-wano','dps','secondary',''),
 ('sukuna-vessel','dps','primary',''),
 ('sukuna-vessel','controller','secondary',''),
 ('sukuna-shibuya','controller','primary',''),
 ('sukuna-shibuya','dps','secondary',''),
 ('yuta-jujutsu-zero','summoner','primary',''),
 ('yuta-jujutsu-zero','support','secondary',''),
 ('yuta-culling-game','summoner','primary',''),
 ('yuta-culling-game','dps','secondary',''),
 ('nezuko-season-1','tank','primary',''),
 ('nezuko-season-1','dps','secondary',''),
 ('nezuko-entertainment-district','tank','primary',''),
 ('nezuko-entertainment-district','dps','secondary','');

INSERT OR IGNORE INTO `version_strategic_traits` (`version_id`,`trait`) VALUES
 ('vegeta-saiyan-saga','close_range'),
 ('vegeta-saiyan-saga','long_range'),
 ('vegeta-super-saiyan-blue','mobility'),
 ('vegeta-super-saiyan-blue','area_damage'),
 ('sasuke-hebi','mobility'),
 ('sasuke-hebi','single_target'),
 ('sasuke-rinnegan','teleportation'),
 ('sasuke-rinnegan','long_range'),
 ('kakashi-sharingan','information'),
 ('kakashi-sharingan','single_target'),
 ('kakashi-war-arc','teleportation'),
 ('kakashi-war-arc','information'),
 ('zoro-enies-lobby','close_range'),
 ('zoro-enies-lobby','single_target'),
 ('zoro-wano','close_range'),
 ('zoro-wano','area_damage'),
 ('sanji-enies-lobby','mobility'),
 ('sanji-enies-lobby','close_range'),
 ('sanji-wano','mobility'),
 ('sanji-wano','single_target'),
 ('sukuna-vessel','single_target'),
 ('sukuna-vessel','close_range'),
 ('sukuna-shibuya','area_damage'),
 ('sukuna-shibuya','anti_regeneration'),
 ('yuta-jujutsu-zero','summoning'),
 ('yuta-jujutsu-zero','close_range'),
 ('yuta-culling-game','summoning'),
 ('yuta-culling-game','adaptation'),
 ('nezuko-season-1','close_range'),
 ('nezuko-season-1','healing'),
 ('nezuko-entertainment-district','healing'),
 ('nezuko-entertainment-district','area_damage');

