import type {Battle} from '@anime/domain/battle';
import {legacyFormsForCharacter} from '@anime/domain/characters';
export type Character = {id:string;name:string;series:string;role:string;cost:number;color:string;description:string;/** @deprecated Compatibility alias for description; version abilities are authoritative for combat data. */ ability:string;/** @deprecated Derived from CharacterVersion records. */ forms:string[];endpoint:string;sourceLabel:string;sourceUrl:string;tags:string[]};
const fighterSeeds:Omit<Character,'ability'|'forms'>[] = [
 {id:'goku',name:'Goku',series:'Dragon Ball',role:'Striker',cost:7,color:'#e99542',description:'Ki control, martial arts, rapid adaptation',endpoint:'Dragon Ball Super anime, episode 131',sourceLabel:'Dragon Ball Official',sourceUrl:'https://en.dragon-ball-official.com/',tags:['martial arts','energy','shonen']},
 {id:'ichigo',name:'Ichigo Kurosaki',series:'Bleach',role:'Striker',cost:6,color:'#e36f53',description:'Zanpakutō combat, spiritual pressure, Getsuga Tenshō',endpoint:'Thousand-Year Blood War anime',sourceLabel:'BLEACH official character page',sourceUrl:'https://bleach-anime.com/character/',tags:['sword','spirit','shonen']},
 {id:'naruto',name:'Naruto Uzumaki',series:'Naruto',role:'Tactician',cost:6,color:'#e7b04f',description:'Shadow clones, Rasengan variants, sensory combat',endpoint:'Naruto Shippuden anime, episode 500',sourceLabel:'NARUTO OFFICIAL SITE',sourceUrl:'https://naruto-official.com/en/',tags:['ninja','energy','shonen']},
 {id:'luffy',name:'Monkey D. Luffy',series:'One Piece',role:'Vanguard',cost:6,color:'#e7666f',description:'Elastic combat, Haki, improvised pressure',endpoint:'Egghead anime arc',sourceLabel:'ONE PIECE.com character directory',sourceUrl:'https://one-piece.com/character/',tags:['pirate','melee','adventure']},
 {id:'tanjiro',name:'Tanjiro Kamado',series:'Demon Slayer',role:'Striker',cost:3,color:'#50bfac',description:'Breathing forms, heightened scent, precision swordplay',endpoint:'Hashira Training anime arc',sourceLabel:'Demon Slayer official character page',sourceUrl:'https://demonslayer-anime.com/hashirageikohen/character/',tags:['sword','demon','new-gen']},
 {id:'levi',name:'Levi Ackerman',series:'Attack on Titan',role:'Scout',cost:3,color:'#98b087',description:'ODM mobility, blades, reconnaissance',endpoint:'Attack on Titan Final Season',sourceLabel:'Attack on Titan official character page',sourceUrl:'https://shingeki.tv/final/character/',tags:['soldier','mobility','strategy']},
 {id:'sakura',name:'Sakura Haruno',series:'Naruto',role:'Support',cost:3,color:'#d68db7',description:'Medical ninjutsu, chakra strength, field support',endpoint:'Naruto Shippuden anime, episode 500',sourceLabel:'NARUTO OFFICIAL SITE',sourceUrl:'https://naruto-official.com/en/',tags:['ninja','healer','support']},
 {id:'shikamaru',name:'Shikamaru Nara',series:'Naruto',role:'Tactician',cost:2,color:'#b0b878',description:'Shadow possession and battlefield planning',endpoint:'Naruto Shippuden anime, episode 500',sourceLabel:'NARUTO OFFICIAL SITE',sourceUrl:'https://naruto-official.com/en/',tags:['ninja','strategy','control']},
 {id:'chopper',name:'Tony Tony Chopper',series:'One Piece',role:'Support',cost:2,color:'#c29ad9',description:'Field medicine and multiple transformation points',endpoint:'Egghead anime arc',sourceLabel:'ONE PIECE.com character directory',sourceUrl:'https://one-piece.com/character/',tags:['pirate','healer','transform']},
 {id:'mikasa',name:'Mikasa Ackerman',series:'Attack on Titan',role:'Vanguard',cost:3,color:'#aa98d9',description:'ODM mobility, blades, close-range cover',endpoint:'Attack on Titan Final Season',sourceLabel:'Attack on Titan official character page',sourceUrl:'https://shingeki.tv/final/character/',tags:['soldier','mobility','melee']},
 {id:'usopp',name:'Usopp',series:'One Piece',role:'Scout',cost:2,color:'#cbb286',description:'Long-range marksmanship, traps, tactical distraction',endpoint:'Egghead anime arc',sourceLabel:'ONE PIECE.com character directory',sourceUrl:'https://one-piece.com/character/',tags:['pirate','ranged','strategy']},
 {id:'rukia',name:'Rukia Kuchiki',series:'Bleach',role:'Control',cost:4,color:'#8cb6db',description:'Ice-type Zanpakutō and zone control',endpoint:'Thousand-Year Blood War anime',sourceLabel:'BLEACH official character page',sourceUrl:'https://bleach-anime.com/character/',tags:['sword','ice','spirit']},
 {id:'deku',name:'Izuku Midoriya',series:'My Hero Academia',role:'Vanguard',cost:5,color:'#58b88d',description:'One For All output, mobility, multiple inherited quirks',endpoint:'My Hero Academia anime, Final Season',sourceLabel:'My Hero Academia official character page',sourceUrl:'https://heroaca.com/character/',tags:['hero','new-gen','melee']},
 {id:'yuji',name:'Yuji Itadori',series:'Jujutsu Kaisen',role:'Striker',cost:4,color:'#df7896',description:'Cursed energy reinforcement and close combat',endpoint:'Shibuya Incident anime arc',sourceLabel:'Jujutsu Kaisen official character page',sourceUrl:'https://jujutsukaisen.jp/character/',tags:['curse','new-gen','melee']},
 {id:'denji',name:'Denji',series:'Chainsaw Man',role:'Vanguard',cost:4,color:'#db7856',description:'Hybrid transformation, chainsaws, high endurance',endpoint:'Chainsaw Man anime season 1',sourceLabel:'Chainsaw Man official character page',sourceUrl:'https://chainsawman.dog/tvseries/character/',tags:['devil','new-gen','transform']},
 {id:'asta',name:'Asta',series:'Black Clover',role:'Control',cost:5,color:'#a9a9bd',description:'Anti-magic swords and close combat',endpoint:'Black Clover anime, episode 170',sourceLabel:'Black Clover official site',sourceUrl:'https://bclover.jp/',tags:['magic','new-gen','sword']},
 {id:'senku',name:'Senku Ishigami',series:'Dr. Stone',role:'Tactician',cost:2,color:'#9fc86d',description:'Scientific planning, invention, logistics',endpoint:'Dr. Stone anime, Science Future',sourceLabel:'Dr. Stone official site',sourceUrl:'https://dr-stone.jp/',tags:['science','new-gen','strategy']},
 {id:'shinra',name:'Shinra Kusakabe',series:'Fire Force',role:'Striker',cost:5,color:'#5f9ed1',description:'Third-generation ignition and aerial mobility',endpoint:'Fire Force anime season 3',sourceLabel:'Fire Force official site',sourceUrl:'https://fireforce-anime.jp/',tags:['fire','new-gen','mobility']},
 {id:'madara',name:'Madara Uchiha',series:'Naruto',role:'Vanguard',cost:7,color:'#8f4d55',description:'Uchiha ocular techniques, battlefield control, Susanoo, and Six Paths-era abilities',endpoint:'Naruto Shippuden · Fourth Shinobi World War',sourceLabel:'NARUTO OFFICIAL SITE',sourceUrl:'https://naruto-official.com/en/',tags:['ninja','uchiha','energy','control']},
 {id:'gojo',name:'Satoru Gojo',series:'Jujutsu Kaisen',role:'Control',cost:6,color:'#79b8e8',description:'Limitless techniques, Six Eyes perception, domain pressure, and reverse cursed technique',endpoint:'Jujutsu Kaisen · Shibuya Incident / manga endpoints',sourceLabel:'Jujutsu Kaisen official character page',sourceUrl:'https://jujutsukaisen.jp/character/',tags:['curse','control','hax','new-gen']},
 {id:'itachi',name:'Itachi Uchiha',series:'Naruto',role:'Tactician',cost:5,color:'#8b6579',description:'Sharingan genjutsu, Amaterasu, Susanoo, and precision shinobi tactics',endpoint:'Naruto Shippuden · Akatsuki / Fourth Shinobi World War',sourceLabel:'NARUTO OFFICIAL SITE',sourceUrl:'https://naruto-official.com/en/',tags:['ninja','uchiha','strategy','hax']},
 {id:'aizen',name:'Sosuke Aizen',series:'Bleach',role:'Control',cost:7,color:'#b69a75',description:'Kyoka Suigetsu hypnosis, high-level Kido, spiritual pressure, and Hogyoku-era evolution',endpoint:'Bleach / Thousand-Year Blood War',sourceLabel:'BLEACH official character page',sourceUrl:'https://bleach-anime.com/en/character/',tags:['spirit','hax','control','strategy']},
 {id:'saitama',name:'Saitama',series:'One-Punch Man',role:'Striker',cost:7,color:'#e6c65a',description:'Overwhelming physical strength, speed, durability, and simple close-range combat',endpoint:'One-Punch Man anime',sourceLabel:'One-Punch Man official character page',sourceUrl:'https://onepunchman-anime.net/character/',tags:['hero','physical','melee','power']},
 {id:'megumi',name:'Megumi Fushiguro',series:'Jujutsu Kaisen',role:'Tactician',cost:3,color:'#586f91',description:'Ten Shadows Technique, shikigami combinations, tactical positioning, and incomplete domain use',endpoint:'Jujutsu Kaisen · Shibuya Incident',sourceLabel:'Jujutsu Kaisen official character page',sourceUrl:'https://jujutsukaisen.jp/character/',tags:['curse','summoning','strategy','new-gen']},
 {id:"vegeta",name:"Vegeta",series:"Dragon Ball",role:"Striker",cost:7,color:"#8fa1dc",description:"Saiyan ki combat, Galick Gun, and Super Saiyan Blue power",endpoint:"Dragon Ball Super anime",sourceLabel:"Dragon Ball Official",sourceUrl:"https://en.dragon-ball-official.com/",tags:["saiyan","energy","martial arts"]},
 {id:"sasuke",name:"Sasuke Uchiha",series:"Naruto",role:"Tactician",cost:6,color:"#737db8",description:"Chidori, Sharingan tactics, and later Rinnegan techniques",endpoint:"Naruto Shippuden · Fourth Shinobi World War",sourceLabel:"NARUTO OFFICIAL SITE",sourceUrl:"https://naruto-official.com/en/",tags:["ninja","uchiha","lightning","strategy"]},
 {id:"kakashi",name:"Kakashi Hatake",series:"Naruto",role:"Tactician",cost:5,color:"#97b4bb",description:"Copy ninja tactics, lightning techniques, and Kamui",endpoint:"Naruto Shippuden anime",sourceLabel:"NARUTO OFFICIAL SITE",sourceUrl:"https://naruto-official.com/en/",tags:["ninja","strategy","lightning","control"]},
 {id:"zoro",name:"Roronoa Zoro",series:"One Piece",role:"Striker",cost:5,color:"#65ac92",description:"Three-sword style, Armament Haki, and decisive melee pressure",endpoint:"One Piece anime · Wano Country",sourceLabel:"ONE PIECE.com character directory",sourceUrl:"https://one-piece.com/character/",tags:["pirate","sword","melee","haki"]},
 {id:"sanji",name:"Sanji",series:"One Piece",role:"Scout",cost:5,color:"#e0b46c",description:"Black Leg Style kicks, Diable Jambe, and high-speed mobility",endpoint:"One Piece anime · Wano Country",sourceLabel:"ONE PIECE.com character directory",sourceUrl:"https://one-piece.com/character/",tags:["pirate","speed","melee","fire"]},
 {id:"sukuna",name:"Ryomen Sukuna",series:"Jujutsu Kaisen",role:"Control",cost:7,color:"#bf6a75",description:"Cleave, Dismantle, and Malevolent Shrine domain techniques",endpoint:"Jujutsu Kaisen anime · Shibuya Incident",sourceLabel:"Jujutsu Kaisen official character page",sourceUrl:"https://jujutsukaisen.jp/character/",tags:["curse","hax","control","domain"]},
 {id:"yuta",name:"Yuta Okkotsu",series:"Jujutsu Kaisen",role:"Support",cost:6,color:"#a2bcd8",description:"Cursed energy reserves, Rika, and copied techniques",endpoint:"Jujutsu Kaisen 0 film / manga later arcs",sourceLabel:"Jujutsu Kaisen official character page",sourceUrl:"https://jujutsukaisen.jp/character/",tags:["curse","sword","summoning","support"]},
 {id:"nezuko",name:"Nezuko Kamado",series:"Demon Slayer",role:"Vanguard",cost:3,color:"#dc91ac",description:"Demon regeneration, close-range kicks, and Blood Demon Art",endpoint:"Demon Slayer anime · Entertainment District",sourceLabel:"Demon Slayer official character page",sourceUrl:"https://demonslayer-anime.com/hashirageikohen/character/",tags:["demon","healer","fire","melee"]},
];
export const fighters:Character[]=fighterSeeds.map(character=>({...character,ability:character.description,forms:legacyFormsForCharacter(character.id)}));
export const clubs = [
 {id:'jjk',name:'Jujutsu Kaisen',season:'Season 1',episodes:24,color:'#a194ec',letters:'呪',description:'Curses, questions, and episode-by-episode theories.',rules:['Tag the highest episode your post reveals.','No manga material in anime-only threads.','Debate the idea without attacking the fan.']},
 {id:'demon',name:'Demon Slayer',season:'Season 1',episodes:26,color:'#53b8aa',letters:'鬼',description:'Take the journey one episode at a time.',rules:['Use the exact episode tag.','Keep future breathing forms out of earlier threads.','Credit art and translations.']},
 {id:'aot',name:'Attack on Titan',season:'Season 1',episodes:25,color:'#c8a778',letters:'進',description:'Every detail matters. Keep the next reveal a surprise.',rules:['No hints disguised as theories.','Tag the last episode needed for context.','Report accidental future reveals.']}
];
export const starterBattles:Battle[] = [
 {id:'goku-ichigo',fighterAId:'goku',fighterBId:'ichigo',fighterAVersionId:'goku-end-z',fighterBVersionId:'ichigo-original-anime-end',a:'Goku',b:'Ichigo Kurosaki',versionA:'End of Dragon Ball Z Goku',versionB:'End of Original Bleach Anime Ichigo',fighterANameSnapshot:'Goku',fighterBNameSnapshot:'Ichigo Kurosaki',fighterAVersionNameSnapshot:'End of Dragon Ball Z Goku',fighterBVersionNameSnapshot:'End of Original Bleach Anime Ichigo',battleType:'knockout',location:'neutral_arena',speed:'equalized',knowledge:'none',prepTime:'none',transformationsAllowed:true,standardEquipment:true,notes:'Neutral empty arena. No preparation. Forms shown by the selected endpoints. Abilities interact across universes.',created:0},
 {id:'naruto-luffy',fighterAId:'naruto',fighterBId:'luffy',fighterAVersionId:'naruto-original-series-end',fighterBVersionId:'luffy-east-blue-end',a:'Naruto Uzumaki',b:'Monkey D. Luffy',versionA:'End of Original Series Naruto',versionB:'East Blue Luffy',fighterANameSnapshot:'Naruto Uzumaki',fighterBNameSnapshot:'Monkey D. Luffy',fighterAVersionNameSnapshot:'End of Original Series Naruto',fighterBVersionNameSnapshot:'East Blue Luffy',battleType:'knockout',location:'neutral_arena',speed:'equalized',knowledge:'none',prepTime:'none',transformationsAllowed:true,standardEquipment:true,notes:'Victory condition: ring out. Circular 100 m arena. No outside assistance. Only abilities shown at these endpoints.',created:0},
 {id:'tanjiro-levi',fighterAId:'tanjiro',fighterBId:'levi',fighterAVersionId:'tanjiro-season-1',fighterBVersionId:'levi-season-1',a:'Tanjiro Kamado',b:'Levi Ackerman',versionA:'Season 1 Tanjiro',versionB:'Season 1 Levi',fighterANameSnapshot:'Tanjiro Kamado',fighterBNameSnapshot:'Levi Ackerman',fighterAVersionNameSnapshot:'Season 1 Tanjiro',fighterBVersionNameSnapshot:'Season 1 Levi',battleType:'knockout',location:'custom',customLocation:'Abandoned city',speed:'normal',knowledge:'none',prepTime:'none',transformationsAllowed:false,standardEquipment:true,notes:'Starting distance: 30 m. Standard equipment only.',created:0}
];
export const seasonalAnime=[
 {id:'dandadan',title:'Dandadan',genres:['supernatural','comedy','new-gen'],why:'Fast supernatural action with character-driven comedy.'},
 {id:'kaiju8',title:'Kaiju No. 8',genres:['monster','hero','new-gen'],why:'Squad tactics and a protagonist balancing human and monster power.'},
 {id:'frieren',title:'Frieren: Beyond Journey’s End',genres:['fantasy','adventure','strategy'],why:'Quiet character growth, magic systems, and reflective fantasy.'},
 {id:'windbreaker',title:'Wind Breaker',genres:['melee','school','new-gen'],why:'Team loyalty and grounded close-range fights.'},
 {id:'sololeveling',title:'Solo Leveling',genres:['fantasy','power','new-gen'],why:'Clear progression, dungeon battles, and escalating power.'},
 {id:'apothecary',title:'The Apothecary Diaries',genres:['mystery','science','strategy'],why:'Deduction, medicine, and court intrigue.'}
];
export const tournamentSeeds=['tanjiro','deku','denji','yuji','shinra','asta','senku','luffy'];
export function weekKey(){const d=new Date(),first=new Date(Date.UTC(d.getUTCFullYear(),0,1));return `${d.getUTCFullYear()}-W${String(Math.ceil(((+d-+first)/86400000+first.getUTCDay()+1)/7)).padStart(2,'0')}`;}
export function tournamentPhase(){const day=new Date().getUTCDay();return day<=2?'quarterfinals':day<=5?'semifinals':'final';}
export function dailyChallenge(){return {day:new Date().toISOString().slice(0,10)};}
