'use client';
import {apiFetch} from '@/services/api';
import {useEffect,useState} from 'react';
export default function ResetPassword(){
 const [token,setToken]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{const value=new URLSearchParams(location.hash.slice(1)).get('token')||new URLSearchParams(location.search).get('token')||'';setToken(value);history.replaceState(null,'','/reset-password')},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);const r=await apiFetch('/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password})}),d:any=await r.json();if(!r.ok)setError(d.error||'Could not reset password.');else setDone(true);setBusy(false)};
 return <main className="auth-shell"><section className="auth-card"><a className="auth-brand" href="/">ANIME CLASH</a><h1>Reset password</h1><p>Choose a new password between 8 and 128 characters.</p>{error&&<div className="auth-error">{error}</div>}{done?<><div className="auth-notice">Password updated. Previous sessions were invalidated.</div><a className="auth-primary auth-button-link" href="/">Continue to Anime Clash</a></>:<form className="auth-form" onSubmit={submit}><label>New password<span className="password-field"><input type={show?'text':'password'} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} maxLength={128} required/><button type="button" onClick={()=>setShow(v=>!v)}>{show?'Hide':'Show'}</button></span></label><label>Confirm password<input type={show?'text':'password'} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} maxLength={128} required/></label><button className="auth-primary" disabled={busy||!token}>{busy?'Updating…':'Reset password'}</button></form>}</section></main>
}
