import {database} from '@/db/raw';
import {clubs,fighters,starterBattles,dailyChallenge,seasonalAnime,tournamentSeeds,weekKey,tournamentPhase} from '@/lib/catalog';
import {BATTLE_TYPES,BATTLE_LOCATIONS,SPEED_RULES,KNOWLEDGE_RULES,PREP_TIMES,VOTE_DIFFICULTIES,normalizeBattle} from '@/lib/battle';
import {abilityById,validateBattleVersionSelection,versionById} from '@/lib/characters';
import {canContribute,getCurrentUser,isAdminUser,type CurrentUser} from '@/lib/auth';
import {sameOrigin} from '@/lib/auth-request';
import {z} from 'zod';

const short=z.string().trim().min(1).max(120), idText=z.string().trim().min(1).max(180), bodyText=z.string().trim().min(3).max(2000);
const avatarUrl=z.string().trim().max(1000).refine(value=>{if(!value)return true;try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password}catch{return false}},{message:'Avatar must be a valid HTTPS URL.'});
const schema=z.discriminatedUnion('action',[
 z.object({action:z.literal('profile'),handle:z.string().trim().regex(/^[a-z0-9_]{3,24}$/),displayName:short,avatarUrl:avatarUrl.optional(),bio:z.string().trim().max(400),favoriteAnime:z.array(short).max(8),favoriteCharacters:z.array(idText).max(8)}),
 z.object({action:z.literal('battle'),fighterAId:idText,fighterBId:idText,fighterAVersionId:idText,fighterBVersionId:idText,battleType:z.enum(BATTLE_TYPES),location:z.enum(BATTLE_LOCATIONS),customLocation:z.string().trim().max(120).optional().default(''),speed:z.enum(SPEED_RULES),knowledge:z.enum(KNOWLEDGE_RULES),prepTime:z.enum(PREP_TIMES),transformationsAllowed:z.boolean(),standardEquipment:z.boolean(),notes:z.string().trim().max(1000)}),
 z.object({action:z.literal('vote'),battle:idText,side:z.enum(['a','b','draw']),difficulty:z.enum(VOTE_DIFFICULTIES),reason:z.string().trim().min(10).max(1500),evidence:z.string().trim().max(300).optional().default(''),structuredEvidenceIds:z.array(idText).max(8).optional()}),
 z.object({action:z.literal('progress'),club:idText,episode:z.number().int().min(0)}),
 z.object({action:z.literal('post'),club:idText,episode:z.number().int().min(0),body:z.string().trim().min(5).max(2000)}),
 z.object({action:z.literal('edit_post'),post:idText,body:z.string().trim().min(5).max(2000)}),
 z.object({action:z.literal('delete_post'),post:idText}),
 z.object({action:z.literal('correct_spoiler'),post:idText,episode:z.number().int().min(0)}),
 z.object({action:z.literal('squad'),name:short,members:z.array(idText).length(5),strategy:z.string().trim().min(10).max(1500),challenge:idText}),
 z.object({action:z.literal('comment'),battle:idText,argumentId:z.number().int().positive(),body:bodyText}),
 z.object({action:z.literal('reaction'),argumentId:z.number().int().positive(),reaction:z.enum(['upvote','dispute'])}),
 z.object({action:z.literal('add_evidence'),battle:idText,argumentId:z.number().int().positive(),reference:z.string().trim().min(3).max(300),context:z.string().trim().max(700)}),
 z.object({action:z.literal('report'),subjectType:z.enum(['post','argument','comment','profile','evidence','squad_submission']),subjectId:idText,reason:z.string().trim().min(5).max(500)}),
 z.object({action:z.literal('squad_challenge'),challengerSquad:idText,opponentSquad:idText,rules:z.string().trim().min(5).max(700)}),
 z.object({action:z.literal('challenge_vote'),challenge:idText,side:z.enum(['challenger','opponent'])}),
 z.object({action:z.literal('tournament_vote'),week:idText,match:idText,pick:idText}),
 z.object({action:z.literal('watchlist'),anime:idText,status:z.enum(['watching','planned','completed','remove'])}),
 z.object({action:z.literal('notification_read'),id:z.union([idText,z.literal('all')])}),
 z.object({action:z.literal('moderation'),report:idText,decision:z.enum(['resolved','dismissed']),deleteContent:z.boolean().default(false)})
]);
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const arr=(value:unknown)=>{try{return JSON.parse(String(value||'[]'))}catch{return []}};
const admin=(user?:CurrentUser|null)=>isAdminUser(user);
async function notify(db:D1Database,user:string,kind:string,message:string,link:string){await db.prepare('INSERT INTO notifications (id,user,kind,message,link,read,created) VALUES (?,?,?,?,?,0,?)').bind(crypto.randomUUID(),user,kind,message,link,Date.now()).run();}
async function profileFor(db:D1Database,user:string){const p=await db.prepare('SELECT handle,display_name AS displayName,avatar_url AS avatarUrl,bio,favorite_anime AS favoriteAnime,favorite_characters AS favoriteCharacters,created FROM profiles WHERE user=?').bind(user).first<any>();return p?{...p,created:Number(p.created),favoriteAnime:arr(p.favoriteAnime),favoriteCharacters:arr(p.favoriteCharacters)}:null;}
async function battleForEvidence(db:D1Database,id:string){const starter=starterBattles.find(b=>b.id===id);if(starter)return starter;const row=await db.prepare('SELECT payload FROM battles WHERE id=?').bind(id).first<{payload:string}>();if(!row)return null;try{return JSON.parse(row.payload) as Record<string,unknown>}catch{return null}}
function aggregateBattleResults(rows:any[]){
 const byBattle=new Map<string,any>();
 for(const row of rows){
  let result=byBattle.get(row.battle);
  if(!result){result={battle:row.battle,a:0,b:0,draw:0,total:0,difficulty:{a:{},b:{}}};byBattle.set(row.battle,result);}
  const n=Number(row.n||0);
  if(row.side==='a'||row.side==='b'||row.side==='draw'){result[row.side]+=n;result.total+=n;}
  if((row.side==='a'||row.side==='b')&&row.difficulty&&VOTE_DIFFICULTIES.includes(row.difficulty)){result.difficulty[row.side][row.difficulty]=(result.difficulty[row.side][row.difficulty]||0)+n;}
 }
 return [...byBattle.values()];
}
async function tournament(db:D1Database,userId?:string){
 const week=weekKey(),phase=tournamentPhase();const rows=(await db.prepare('SELECT match,pick,COUNT(*) AS n FROM tournament_votes WHERE week=? GROUP BY match,pick').bind(week).all<any>()).results;
 const my=userId?(await db.prepare('SELECT match,pick FROM tournament_votes WHERE week=? AND user=?').bind(week,userId).all<any>()).results:[];
 const counts=(match:string,id:string)=>Number(rows.find(r=>r.match===match&&r.pick===id)?.n||0);
 const winner=(match:string,a:string,b:string)=>counts(match,b)>counts(match,a)?b:a;
 const q=[['q1',tournamentSeeds[0],tournamentSeeds[1]],['q2',tournamentSeeds[2],tournamentSeeds[3]],['q3',tournamentSeeds[4],tournamentSeeds[5]],['q4',tournamentSeeds[6],tournamentSeeds[7]]];
 const s=[['s1',winner(...q[0] as [string,string,string]),winner(...q[1] as [string,string,string])],['s2',winner(...q[2] as [string,string,string]),winner(...q[3] as [string,string,string])]];
 const f=[['f1',winner(...s[0] as [string,string,string]),winner(...s[1] as [string,string,string])]];
 const active=phase==='quarterfinals'?q:phase==='semifinals'?s:f;const all=[...q,...s,...f].map(([id,a,b])=>({id,a,b,aVotes:counts(id,a),bVotes:counts(id,b),myPick:my.find(v=>v.match===id)?.pick||null,active:active.some(m=>m[0]===id)}));
 const leaderboard=tournamentSeeds.map(id=>({id,votes:rows.filter(r=>r.pick===id).reduce((n,r)=>n+Number(r.n),0)})).sort((a,b)=>b.votes-a.votes);
 return {week,title:'New-Gen Crown',phase,matches:all,leaderboard,champion:phase==='final'&&all.find(m=>m.id==='f1')?winner('f1',f[0][1],f[0][2]):null};
}

export async function GET(req:Request){try{
 const user=await getCurrentUser(),db=database(),url=new URL(req.url),mode=url.searchParams.get('mode'),club=url.searchParams.get('club'),battle=url.searchParams.get('battle'),profile=url.searchParams.get('profile'),squadId=url.searchParams.get('squad');
 if(squadId){const s=await db.prepare(`SELECT s.id,s.name,s.members,s.strategy,s.challenge,COALESCE(p.handle,'anime_fan') AS handle FROM squads s LEFT JOIN profiles p ON p.user=s.owner WHERE s.id=?`).bind(squadId).first<any>();return s?json({squad:{...s,members:arr(s.members)}}):json({error:'Squad not found'},404);}
 if(club){const c=clubs.find(c=>c.id===club);if(!c)return json({error:'Unknown club'},400);const row=user?await db.prepare('SELECT episode FROM progress WHERE user=? AND club=?').bind(user.userId,club).first<{episode:number}>():null,episode=row?.episode??0;
 const posts=(await db.prepare(`SELECT po.id,po.user,po.episode,po.body,po.edited,po.created,COALESCE(pr.handle,'anime_fan') AS handle,COALESCE(pr.display_name,'Anime fan') AS displayName FROM posts po LEFT JOIN profiles pr ON pr.user=po.user WHERE po.club=? AND po.episode<=? AND po.deleted=0 ORDER BY po.created DESC LIMIT 100`).bind(club,episode).all<any>()).results.map(p=>({...p,owned:user?.userId===p.user}));
 const locked=await db.prepare('SELECT COUNT(*) AS n FROM posts WHERE club=? AND episode>? AND deleted=0').bind(club,episode).first<{n:number}>();return json({episode,posts,locked:locked?.n??0,rules:c.rules,isAdmin:admin(user)});}
 if(profile){let p:any;if(profile==='me'){if(!user)return json({error:'Sign in to view your profile.'},401);p=await db.prepare('SELECT * FROM profiles WHERE user=?').bind(user.userId).first<any>();}else p=await db.prepare('SELECT p.* FROM profiles p JOIN users u ON u.id=p.user WHERE p.handle=? AND u.profile_completed=1 AND u.email_verified=1').bind(profile.toLowerCase()).first<any>();if(!p)return json({profile:null});
 const [squads,record,progressRows]=await Promise.all([db.prepare('SELECT id,name,members,strategy,challenge FROM squads WHERE owner=? ORDER BY created DESC LIMIT 12').bind(p.user).all<any>(),db.prepare('SELECT COUNT(*) AS total,SUM(CASE WHEN side="a" THEN 1 ELSE 0 END) AS sideA,SUM(CASE WHEN side="b" THEN 1 ELSE 0 END) AS sideB,SUM(CASE WHEN side="draw" THEN 1 ELSE 0 END) AS draws FROM votes WHERE user=?').bind(p.user).first<any>(),db.prepare('SELECT club,episode FROM progress WHERE user=?').bind(p.user).all<any>()]);return json({profile:{handle:p.handle,displayName:p.display_name,avatarUrl:p.avatar_url||null,bio:p.bio,favoriteAnime:arr(p.favorite_anime),favoriteCharacters:arr(p.favorite_characters),created:Number(p.created),owned:user?.userId===p.user},squads:squads.results.map(s=>({...s,members:arr(s.members)})),record,progress:progressRows.results});}
 if(mode==='notifications'){if(!user)return json({error:'Sign in to see notifications.'},401);const tourId=`tournament:${weekKey()}`;if(!await db.prepare('SELECT id FROM notifications WHERE user=? AND id=?').bind(user.userId,tourId).first())await db.prepare('INSERT INTO notifications (id,user,kind,message,link,read,created) VALUES (?,?,"tournament",?,?,0,?)').bind(tourId,user.userId,`The ${weekKey()} New-Gen Crown tournament is open.`,'/?view=tournaments',Date.now()).run();const notes=(await db.prepare('SELECT id,kind,message,link,read,created FROM notifications WHERE user=? ORDER BY created DESC LIMIT 80').bind(user.userId).all<any>()).results;return json({notifications:notes,unread:notes.filter(n=>!n.read).length});}
 if(mode==='tournaments')return json(await tournament(db,user?.userId));
 if(mode==='challenges'){const challenges=(await db.prepare(`SELECT c.id,c.rules,c.status,c.created,sa.id AS challengerId,sa.name AS challengerName,sa.members AS challengerMembers,sa.strategy AS challengerStrategy,sb.id AS opponentId,sb.name AS opponentName,sb.members AS opponentMembers,sb.strategy AS opponentStrategy,pa.handle AS challengerHandle,pb.handle AS opponentHandle,(SELECT COUNT(*) FROM challenge_votes v WHERE v.challenge=c.id AND v.side='challenger') AS challengerVotes,(SELECT COUNT(*) FROM challenge_votes v WHERE v.challenge=c.id AND v.side='opponent') AS opponentVotes FROM squad_challenges c JOIN squads sa ON sa.id=c.challenger_squad JOIN squads sb ON sb.id=c.opponent_squad LEFT JOIN profiles pa ON pa.user=sa.owner LEFT JOIN profiles pb ON pb.user=sb.owner WHERE c.status='open' ORDER BY c.created DESC LIMIT 30`).all<any>()).results.map(c=>({...c,challengerMembers:arr(c.challengerMembers),opponentMembers:arr(c.opponentMembers)}));const publicSquads=(await db.prepare(`SELECT s.id,s.name,s.members,s.strategy,COALESCE(p.handle,'anime_fan') AS handle FROM squads s LEFT JOIN profiles p ON p.user=s.owner ORDER BY s.created DESC LIMIT 50`).all<any>()).results.map(s=>({...s,members:arr(s.members)}));return json({challenges,publicSquads,mySquads:user?(await db.prepare('SELECT id,name,members,strategy FROM squads WHERE owner=?').bind(user.userId).all<any>()).results.map(s=>({...s,members:arr(s.members)})):[]});}
 if(mode==='discover'){const current=user?await profileFor(db,user.userId):null;const profiles=(await db.prepare('SELECT p.handle,p.display_name AS displayName,p.avatar_url AS avatarUrl,p.bio,p.favorite_anime AS favoriteAnime,p.favorite_characters AS favoriteCharacters FROM profiles p JOIN users u ON u.id=p.user WHERE u.profile_completed=1 AND u.email_verified=1 ORDER BY p.updated DESC LIMIT 60').all<any>()).results.map(p=>{const anime=arr(p.favoriteAnime),chars=arr(p.favoriteCharacters),mineA=current?.favoriteAnime||[],mineC=current?.favoriteCharacters||[];const overlap=[...anime.filter((x:string)=>mineA.includes(x)),...chars.filter((x:string)=>mineC.includes(x))];return {...p,favoriteAnime:anime,favoriteCharacters:chars,match:current?Math.min(99,25+overlap.length*15):null};}).filter(p=>p.handle!==current?.handle).sort((a,b)=>(b.match||0)-(a.match||0));const tags=(current?.favoriteCharacters||[]).flatMap((id:string)=>fighters.find(f=>f.id===id)?.tags||[]);const recs=seasonalAnime.map(a=>({...a,score:a.genres.filter(g=>tags.includes(g)).length})).sort((a,b)=>b.score-a.score);const watch=user?(await db.prepare('SELECT anime,status FROM watchlist WHERE user=?').bind(user.userId).all<any>()).results:[];return json({profiles,recommendations:recs,watchlist:watch});}
 if(mode==='moderation'){if(!user||!admin(user))return json({error:'Admin access required.'},403);const reports=(await db.prepare('SELECT * FROM reports WHERE status="open" ORDER BY created ASC LIMIT 100').all<any>()).results;return json({reports});}
 const [bs,vs,ps,ss,notes,currentProfile]=await Promise.all([db.prepare('SELECT id,payload,created FROM battles ORDER BY created DESC LIMIT 100').all<any>(),db.prepare('SELECT battle,side,difficulty,COUNT(*) AS n FROM votes GROUP BY battle,side,difficulty').all<any>(),user?db.prepare('SELECT club,episode FROM progress WHERE user=?').bind(user.userId).all<any>():Promise.resolve({results:[]}),user?db.prepare('SELECT id,name,members,strategy,challenge FROM squads WHERE owner=? ORDER BY created DESC LIMIT 50').bind(user.userId).all<any>():Promise.resolve({results:[]}),user?db.prepare('SELECT COUNT(*) AS n FROM notifications WHERE user=? AND read=0').bind(user.userId).first<{n:number}>():null,user?profileFor(db,user.userId):null]);
 let debate:any[]=[];if(battle){
  debate=(await db.prepare(`SELECT v.rowid AS argumentId,v.user AS argumentUser,v.side,v.difficulty,v.reason,v.evidence,v.created,COALESCE(p.handle,'anime_fan') AS handle,COALESCE(p.display_name,'Anime fan') AS displayName,(SELECT COUNT(*) FROM reactions r WHERE r.subject_type='argument' AND r.subject_id=CAST(v.rowid AS TEXT) AND r.reaction='upvote') AS upvotes,(SELECT COUNT(*) FROM reactions r WHERE r.subject_type='argument' AND r.subject_id=CAST(v.rowid AS TEXT) AND r.reaction='dispute') AS disputes,(SELECT r.reaction FROM reactions r WHERE r.subject_type='argument' AND r.subject_id=CAST(v.rowid AS TEXT) AND r.user=? LIMIT 1) AS myReaction FROM votes v LEFT JOIN profiles p ON p.user=v.user WHERE v.battle=? ORDER BY v.created DESC LIMIT 100`).bind(user?.userId||'',battle).all<any>()).results;
  const [comments,evidenceRows,structuredRows]=await Promise.all([
   db.prepare(`SELECT c.id,c.argument_user AS argumentUser,c.body,c.created,COALESCE(p.handle,'anime_fan') AS handle FROM comments c LEFT JOIN profiles p ON p.user=c.user WHERE c.battle=? ORDER BY c.created ASC LIMIT 500`).bind(battle).all<any>(),
   db.prepare(`SELECT ae.id,ae.argument_user AS argumentUser,ae.reference,ae.context,ae.created,COALESCE(p.handle,'anime_fan') AS handle FROM argument_evidence ae LEFT JOIN profiles p ON p.user=ae.contributor WHERE ae.battle=? ORDER BY ae.created ASC LIMIT 300`).bind(battle).all<any>(),
   db.prepare(`SELECT l.argument_user AS argumentUser,l.evidence_id AS evidenceId,l.linked_by AS linkedBy,l.created AS linkCreated,COALESCE(lp.handle,'anime_fan') AS linkedByHandle,er.id,er.character_id AS characterId,er.version_id AS versionId,er.ability_id AS abilityId,er.source_type AS sourceType,er.series,er.category,er.title,er.description,er.episode,er.timestamp,er.chapter,er.page,er.submitted_by AS submittedBy,er.created,er.updated,COALESCE(er.deleted,1) AS deleted,COALESCE(ep.handle,'anime_fan') AS submittedByHandle FROM argument_evidence_links l LEFT JOIN evidence_records er ON er.id=l.evidence_id LEFT JOIN profiles lp ON lp.user=l.linked_by LEFT JOIN profiles ep ON ep.user=er.submitted_by WHERE l.battle=? ORDER BY l.created ASC LIMIT 300`).bind(battle).all<any>()
  ]);
  for(const a of debate){
   const argumentUser=a.argumentUser;
   a.owned=Boolean(user&&user.userId===argumentUser);
   a.comments=comments.results.filter((c:any)=>c.argumentUser===argumentUser).map((c:any)=>({id:c.id,body:c.body,created:c.created,handle:c.handle}));
   a.addedEvidence=evidenceRows.results.filter((e:any)=>e.argumentUser===argumentUser).map((e:any)=>({id:e.id,reference:e.reference,context:e.context,created:e.created,handle:e.handle}));
   a.structuredEvidence=structuredRows.results.filter((e:any)=>e.argumentUser===argumentUser).map((e:any)=>{const deleted=Boolean(e.deleted)||!e.id;return {kind:'structured',id:e.evidenceId,evidenceId:e.evidenceId,linkedByHandle:e.linkedByHandle,linkCreated:Number(e.linkCreated),linkOwned:Boolean(user&&e.linkedBy===user.userId),canUnlink:Boolean(user&&(e.linkedBy===user.userId||argumentUser===user.userId||admin(user))),deleted,record:deleted?null:{id:e.id,characterId:e.characterId,characterName:fighters.find(f=>f.id===e.characterId)?.name||e.characterId,versionId:e.versionId||null,versionName:e.versionId?versionById(e.versionId)?.name||null:null,abilityId:e.abilityId||null,abilityName:e.abilityId?abilityById(e.abilityId)?.name||null:null,sourceType:e.sourceType,series:e.series,category:e.category,title:e.title,description:e.description,episode:e.episode==null?null:Number(e.episode),timestamp:e.timestamp||null,chapter:e.chapter==null?null:Number(e.chapter),page:e.page==null?null:Number(e.page),submittedByHandle:e.submittedByHandle,created:Number(e.created),updated:Number(e.updated),owned:Boolean(user&&e.submittedBy===user.userId)}};});
   a.myReaction=a.myReaction||null;delete a.argumentUser;
  }
 }
 const myVotes=user?(await db.prepare('SELECT battle,side,difficulty,reason,evidence FROM votes WHERE user=?').bind(user.userId).all<any>()).results:[];
 const battles=[...bs.results.map((b:any)=>normalizeBattle({...JSON.parse(b.payload),id:b.id,created:b.created})),...starterBattles];
 return json({battles,votes:vs.results,results:aggregateBattleResults(vs.results),myVotes,progress:ps.results,squads:ss.results.map((s:any)=>({...s,members:arr(s.members)})),debate,user:!!user,auth:user?{emailVerified:user.emailVerified,profileCompleted:user.profileCompleted,requiresEmailVerification:!user.emailVerified}:null,profile:currentProfile,isAdmin:admin(user),unread:notes?.n||0,challenge:dailyChallenge()});
 }catch(e){console.error('Community load failed',e);return json({error:'Could not load the community. Please try again.'},503);}}

export async function POST(req:Request){try{
 if(!sameOrigin(req))return json({error:'Invalid origin'},403);const user=await getCurrentUser();if(!user)return json({error:'Sign in to save your contribution.'},401);const raw=await req.text();if(raw.length>15000)return json({error:'Submission is too large'},413);let parsed;try{parsed=schema.safeParse(JSON.parse(raw));}catch{return json({error:'Invalid submission'},400);}if(!parsed.success)return json({error:'Check the fields and provide the required details.'},400);const d=parsed.data,db=database(),now=Date.now();if(d.action!=='profile'&&!canContribute(user))return json({error:user.profileCompleted?'Verify your email before contributing.':'Complete your profile before contributing.'},403);let id=crypto.randomUUID();
 if(d.action==='profile'){try{await db.batch([db.prepare(`INSERT INTO profiles (user,handle,display_name,avatar_url,bio,favorite_anime,favorite_characters,created,updated) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(user) DO UPDATE SET handle=excluded.handle,display_name=excluded.display_name,avatar_url=CASE WHEN excluded.avatar_url IS NULL THEN profiles.avatar_url ELSE excluded.avatar_url END,bio=excluded.bio,favorite_anime=excluded.favorite_anime,favorite_characters=excluded.favorite_characters,updated=excluded.updated`).bind(user.userId,d.handle.toLowerCase(),d.displayName,d.avatarUrl===undefined?null:d.avatarUrl,d.bio,JSON.stringify(d.favoriteAnime),JSON.stringify(d.favoriteCharacters),now,now),db.prepare('UPDATE users SET profile_completed=1,updated=? WHERE id=?').bind(now,user.userId)]);}catch{return json({error:'That handle is already taken.'},409);}}
 if(d.action==='battle'){
  const fighterA=fighters.find(f=>f.id===d.fighterAId),fighterB=fighters.find(f=>f.id===d.fighterBId);
  if(!fighterA||!fighterB)return json({error:'Choose fighters from the character catalog.'},400);
  if(fighterA.id===fighterB.id)return json({error:'Choose two different fighters.'},400);
  const versionA=versionById(d.fighterAVersionId),versionB=versionById(d.fighterBVersionId);
  if(!versionA||!versionB||!validateBattleVersionSelection(fighterA.id,versionA.id,fighterB.id,versionB.id))return json({error:'Choose a valid canonical version belonging to each fighter.'},400);
  if(d.location==='custom'&&!d.customLocation.trim())return json({error:'Describe the custom battle location.'},400);
  const payload={fighterAId:fighterA.id,fighterBId:fighterB.id,fighterAVersionId:versionA.id,fighterBVersionId:versionB.id,fighterANameSnapshot:fighterA.name,fighterBNameSnapshot:fighterB.name,fighterAVersionNameSnapshot:versionA.name,fighterBVersionNameSnapshot:versionB.name,battleType:d.battleType,location:d.location,customLocation:d.location==='custom'?d.customLocation.trim():'',speed:d.speed,knowledge:d.knowledge,prepTime:d.prepTime,transformationsAllowed:d.transformationsAllowed,standardEquipment:d.standardEquipment,notes:d.notes};
  await db.prepare('INSERT INTO battles (id,owner,payload,created) VALUES (?,?,?,?)').bind(id,user.userId,JSON.stringify(payload),now).run();
 }
 if(d.action==='vote'){
  const battleRecord=await battleForEvidence(db,d.battle);if(!battleRecord)return json({error:'Battle not found'},404);
  if((d.side==='draw')!==(d.difficulty==='inconclusive'))return json({error:'Draw votes must use Inconclusive; fighter votes require a difficulty.'},400);
  const structuredIds=d.structuredEvidenceIds?[...new Set(d.structuredEvidenceIds)]:undefined;
  if(d.evidence.trim().length<3&&(!structuredIds||!structuredIds.length))return json({error:'Add a source reference or choose at least one feat from the library.'},400);
  if(structuredIds?.length){
   const placeholders=structuredIds.map(()=>'?').join(',');
   const rows=(await db.prepare(`SELECT id,character_id AS characterId,version_id AS versionId FROM evidence_records WHERE deleted=0 AND id IN (${placeholders})`).bind(...structuredIds).all<any>()).results;
   if(rows.length!==structuredIds.length)return json({error:'One or more selected feats are unavailable.'},400);
   const allowedCharacters=[String((battleRecord as any).fighterAId||''),String((battleRecord as any).fighterBId||'')].filter(Boolean);
   const allowedVersions=[String((battleRecord as any).fighterAVersionId||''),String((battleRecord as any).fighterBVersionId||'')].filter(Boolean);
   if(!allowedCharacters.length||rows.some((row:any)=>!allowedCharacters.includes(row.characterId)))return json({error:'Choose feats for the fighters in this battle.'},400);
   if(allowedVersions.length===2&&rows.some((row:any)=>!row.versionId||!allowedVersions.includes(row.versionId)))return json({error:'Choose feats for the exact versions selected in this battle.'},400);
   if(allowedVersions.length!==2&&rows.some((row:any)=>row.versionId))return json({error:'Battles without two trustworthy stable version IDs cannot accept new version-scoped feats. Use manual evidence.'},400);
  }
  await db.prepare('INSERT INTO votes (battle,user,side,difficulty,reason,evidence,created) VALUES (?,?,?,?,?,?,?) ON CONFLICT(battle,user) DO UPDATE SET side=excluded.side,difficulty=excluded.difficulty,reason=excluded.reason,evidence=excluded.evidence,created=excluded.created').bind(d.battle,user.userId,d.side,d.difficulty,d.reason,d.evidence,now).run();
  if(structuredIds){
   await db.prepare('DELETE FROM argument_evidence_links WHERE battle=? AND argument_user=? AND linked_by=?').bind(d.battle,user.userId,user.userId).run();
   for(const evidenceId of structuredIds)await db.prepare('INSERT OR IGNORE INTO argument_evidence_links (battle,argument_user,evidence_id,linked_by,created) VALUES (?,?,?,?,?)').bind(d.battle,user.userId,evidenceId,user.userId,now).run();
  }
  id=d.battle;
 }
 if(d.action==='progress'||d.action==='post'){const c=clubs.find(c=>c.id===d.club);if(!c||d.episode>c.episodes)return json({error:'Episode is outside this club’s season.'},400);if(d.action==='progress'){const old=await db.prepare('SELECT episode FROM progress WHERE user=? AND club=?').bind(user.userId,d.club).first<{episode:number}>();await db.prepare('INSERT INTO progress (user,club,episode) VALUES (?,?,?) ON CONFLICT(user,club) DO UPDATE SET episode=excluded.episode').bind(user.userId,d.club,d.episode).run();const unlocked=await db.prepare('SELECT COUNT(*) AS n FROM posts WHERE club=? AND episode>? AND episode<=? AND deleted=0').bind(d.club,old?.episode||0,d.episode).first<{n:number}>();if((unlocked?.n||0)>0)await notify(db,user.userId,'club',`${unlocked!.n} ${c.name} discussions are now unlocked.`,`/?view=clubs&club=${d.club}`);}else{const p=await db.prepare('SELECT episode FROM progress WHERE user=? AND club=?').bind(user.userId,d.club).first<{episode:number}>();if(d.episode>(p?.episode??0))return json({error:'Set your viewing progress before discussing that episode.'},400);await db.prepare('INSERT INTO posts (id,user,club,episode,body,edited,deleted,created) VALUES (?,?,?,?,?,0,0,?)').bind(id,user.userId,d.club,d.episode,d.body,now).run();}}
 if(d.action==='edit_post'){const post=await db.prepare('SELECT user FROM posts WHERE id=? AND deleted=0').bind(d.post).first<any>();if(!post||(post.user!==user.userId&&!admin(user)))return json({error:'You cannot edit this post.'},403);await db.prepare('UPDATE posts SET body=?,edited=1 WHERE id=?').bind(d.body,d.post).run();}
 if(d.action==='delete_post'){const post=await db.prepare('SELECT user FROM posts WHERE id=?').bind(d.post).first<any>();if(!post||(post.user!==user.userId&&!admin(user)))return json({error:'You cannot delete this post.'},403);await db.prepare('UPDATE posts SET deleted=1,body="[removed]" WHERE id=?').bind(d.post).run();}
 if(d.action==='correct_spoiler'){const post=await db.prepare('SELECT user,club FROM posts WHERE id=? AND deleted=0').bind(d.post).first<any>(),c=clubs.find(c=>c.id===post?.club);if(!post||(!admin(user)&&post.user!==user.userId)||!c||d.episode>c.episodes)return json({error:'Spoiler tag cannot be changed.'},403);await db.prepare('UPDATE posts SET episode=?,edited=1 WHERE id=?').bind(d.episode,d.post).run();}
 if(d.action==='squad'){const members=d.members.map(m=>fighters.find(f=>f.id===m));if(new Set(d.members).size!==5||members.some(m=>!m)||members.reduce((s,m)=>s+(m?.cost??0),0)>20)return json({error:'Choose five unique fighters within 20 points.'},400);if(d.challenge!==dailyChallenge().day)return json({error:'A new daily challenge is available. Refresh before saving.'},409);await db.prepare('INSERT INTO squads (id,owner,name,members,strategy,challenge,created) VALUES (?,?,?,?,?,?,?)').bind(id,user.userId,d.name,JSON.stringify(d.members),d.strategy,d.challenge,now).run();}
 if(d.action==='comment'){const arg=await db.prepare('SELECT user,battle FROM votes WHERE rowid=?').bind(d.argumentId).first<any>();if(!arg||arg.battle!==d.battle)return json({error:'Argument not found.'},404);await db.prepare('INSERT INTO comments (id,battle,argument_user,user,body,created) VALUES (?,?,?,?,?,?)').bind(id,d.battle,arg.user,user.userId,d.body,now).run();if(arg.user!==user.userId)await notify(db,arg.user,'reply','Someone replied to your battle argument.',`/?battle=${d.battle}`);}
 if(d.action==='reaction'){const arg=await db.prepare('SELECT rowid FROM votes WHERE rowid=?').bind(d.argumentId).first();if(!arg)return json({error:'Argument not found.'},404);await db.prepare(`INSERT INTO reactions (subject_type,subject_id,user,reaction,created) VALUES ('argument',?,?,?,?) ON CONFLICT(subject_type,subject_id,user) DO UPDATE SET reaction=excluded.reaction,created=excluded.created`).bind(String(d.argumentId),user.userId,d.reaction,now).run();}
 if(d.action==='add_evidence'){const arg=await db.prepare('SELECT user,battle FROM votes WHERE rowid=?').bind(d.argumentId).first<any>();if(!arg||arg.battle!==d.battle)return json({error:'Argument not found.'},404);await db.prepare('INSERT INTO argument_evidence (id,battle,argument_user,contributor,reference,context,created) VALUES (?,?,?,?,?,?,?)').bind(id,d.battle,arg.user,user.userId,d.reference,d.context,now).run();}
 if(d.action==='report'){await db.prepare('INSERT INTO reports (id,reporter,subject_type,subject_id,reason,status,created) VALUES (?,?,?,?,?,"open",?)').bind(id,user.userId,d.subjectType,d.subjectId,d.reason,now).run();}
 if(d.action==='squad_challenge'){if(d.challengerSquad===d.opponentSquad)return json({error:'Choose two different squads.'},400);const a=await db.prepare('SELECT owner FROM squads WHERE id=?').bind(d.challengerSquad).first<any>(),b=await db.prepare('SELECT owner FROM squads WHERE id=?').bind(d.opponentSquad).first<any>();if(!a||!b||a.owner!==user.userId)return json({error:'Choose one of your squads as the challenger.'},403);await db.prepare('INSERT INTO squad_challenges (id,challenger,challenger_squad,opponent_squad,rules,status,created) VALUES (?,?,?,?,?,"open",?)').bind(id,user.userId,d.challengerSquad,d.opponentSquad,d.rules,now).run();if(b.owner!==user.userId)await notify(db,b.owner,'challenge','Your squad received a new challenge.','/?view=challenges');}
 if(d.action==='challenge_vote'){if(!await db.prepare('SELECT id FROM squad_challenges WHERE id=? AND status="open"').bind(d.challenge).first())return json({error:'Challenge not found.'},404);await db.prepare('INSERT INTO challenge_votes (challenge,user,side,created) VALUES (?,?,?,?) ON CONFLICT(challenge,user) DO UPDATE SET side=excluded.side,created=excluded.created').bind(d.challenge,user.userId,d.side,now).run();}
 if(d.action==='tournament_vote'){const t=await tournament(db,user.userId),m=t.matches.find((m:any)=>m.id===d.match&&m.active);if(d.week!==t.week||!m||![m.a,m.b].includes(d.pick))return json({error:'That tournament round is closed.'},409);await db.prepare('INSERT INTO tournament_votes (week,match,user,pick,created) VALUES (?,?,?,?,?) ON CONFLICT(week,match,user) DO UPDATE SET pick=excluded.pick,created=excluded.created').bind(d.week,d.match,user.userId,d.pick,now).run();}
 if(d.action==='watchlist'){if(!seasonalAnime.some(a=>a.id===d.anime))return json({error:'Anime not found.'},404);if(d.status==='remove')await db.prepare('DELETE FROM watchlist WHERE user=? AND anime=?').bind(user.userId,d.anime).run();else await db.prepare('INSERT INTO watchlist (user,anime,status,created) VALUES (?,?,?,?) ON CONFLICT(user,anime) DO UPDATE SET status=excluded.status').bind(user.userId,d.anime,d.status,now).run();}
 if(d.action==='notification_read'){if(d.id==='all')await db.prepare('UPDATE notifications SET read=1 WHERE user=?').bind(user.userId).run();else await db.prepare('UPDATE notifications SET read=1 WHERE id=? AND user=?').bind(d.id,user.userId).run();}
 if(d.action==='moderation'){if(!admin(user))return json({error:'Admin access required.'},403);const report=await db.prepare('SELECT * FROM reports WHERE id=? AND status="open"').bind(d.report).first<any>();if(!report)return json({error:'Report not found.'},404);if(d.deleteContent&&report.subject_type==='post')await db.prepare('UPDATE posts SET deleted=1,body="[removed by moderator]" WHERE id=?').bind(report.subject_id).run();if(d.deleteContent&&report.subject_type==='comment')await db.prepare('DELETE FROM comments WHERE id=?').bind(report.subject_id).run();if(d.deleteContent&&report.subject_type==='evidence'){const structured=await db.prepare('SELECT id FROM evidence_records WHERE id=?').bind(report.subject_id).first();if(structured)await db.prepare('UPDATE evidence_records SET deleted=1,deleted_at=?,updated=? WHERE id=?').bind(now,now,report.subject_id).run();else await db.prepare('DELETE FROM argument_evidence WHERE id=?').bind(report.subject_id).run();}if(d.deleteContent&&report.subject_type==='squad_submission')await db.prepare('UPDATE squad_submissions SET removed=1,updated=? WHERE id=?').bind(now,report.subject_id).run();await db.prepare('UPDATE reports SET status=? WHERE id=?').bind(d.decision,d.report).run();}
 return json({ok:true,id});
 }catch(e){console.error('Community save failed',e);return json({error:'Could not save. Your draft is still here; please try again.'},503);}}
