import type {Battle} from '@/lib/battle';
export type Character = {id:string;name:string;series:string;role:string;cost:number;color:string;ability:string;forms:string[];endpoint:string;sourceLabel:string;sourceUrl:string;tags:string[]};
export const fighters:Character[] = [
 {id:'goku',name:'Goku',series:'Dragon Ball',role:'Striker',cost:7,color:'#e99542',ability:'Ki control, martial arts, rapid adaptation',forms:['Base','Super Saiyan','Super Saiyan God','Ultra Instinct'],endpoint:'Dragon Ball Super anime, episode 131',sourceLabel:'Dragon Ball Official',sourceUrl:'https://en.dragon-ball-official.com/',tags:['martial arts','energy','shonen']},
 {id:'ichigo',name:'Ichigo Kurosaki',series:'Bleach',role:'Striker',cost:6,color:'#e36f53',ability:'Zanpakutō combat, spiritual pressure, Getsuga Tenshō',forms:['Shikai','Bankai','Hollowfication'],endpoint:'Thousand-Year Blood War anime',sourceLabel:'BLEACH official character page',sourceUrl:'https://bleach-anime.com/character/',tags:['sword','spirit','shonen']},
 {id:'naruto',name:'Naruto Uzumaki',series:'Naruto',role:'Tactician',cost:6,color:'#e7b04f',ability:'Shadow clones, Rasengan variants, sensory combat',forms:['Base','Sage Mode','Kurama Chakra Mode'],endpoint:'Naruto Shippuden anime, episode 500',sourceLabel:'NARUTO OFFICIAL SITE',sourceUrl:'https://naruto-official.com/en/',tags:['ninja','energy','shonen']},
 {id:'luffy',name:'Monkey D. Luffy',series:'One Piece',role:'Vanguard',cost:6,color:'#e7666f',ability:'Elastic combat, Haki, improvised pressure',forms:['Base','Gear 2','Gear 4','Gear 5'],endpoint:'Egghead anime arc',sourceLabel:'ONE PIECE.com character directory',sourceUrl:'https://one-piece.com/character/',tags:['pirate','melee','adventure']},
 {id:'tanjiro',name:'Tanjiro Kamado',series:'Demon Slayer',role:'Striker',cost:3,color:'#50bfac',ability:'Breathing forms, heightened scent, precision swordplay',forms:['Water Breathing','Hinokami Kagura'],endpoint:'Hashira Training anime arc',sourceLabel:'Demon Slayer official character page',sourceUrl:'https://demonslayer-anime.com/hashirageikohen/character/',tags:['sword','demon','new-gen']},
 {id:'levi',name:'Levi Ackerman',series:'Attack on Titan',role:'Scout',cost:3,color:'#98b087',ability:'ODM mobility, blades, reconnaissance',forms:['Standard ODM gear','Thunder spears'],endpoint:'Attack on Titan Final Season',sourceLabel:'Attack on Titan official character page',sourceUrl:'https://shingeki.tv/final/character/',tags:['soldier','mobility','strategy']},
 {id:'sakura',name:'Sakura Haruno',series:'Naruto',role:'Support',cost:3,color:'#d68db7',ability:'Medical ninjutsu, chakra strength, field support',forms:['Byakugō Seal'],endpoint:'Naruto Shippuden anime, episode 500',sourceLabel:'NARUTO OFFICIAL SITE',sourceUrl:'https://naruto-official.com/en/',tags:['ninja','healer','support']},
 {id:'shikamaru',name:'Shikamaru Nara',series:'Naruto',role:'Tactician',cost:2,color:'#b0b878',ability:'Shadow possession and battlefield planning',forms:['Standard shinobi equipment'],endpoint:'Naruto Shippuden anime, episode 500',sourceLabel:'NARUTO OFFICIAL SITE',sourceUrl:'https://naruto-official.com/en/',tags:['ninja','strategy','control']},
 {id:'chopper',name:'Tony Tony Chopper',series:'One Piece',role:'Support',cost:2,color:'#c29ad9',ability:'Field medicine and multiple transformation points',forms:['Brain Point','Guard Point','Monster Point'],endpoint:'Egghead anime arc',sourceLabel:'ONE PIECE.com character directory',sourceUrl:'https://one-piece.com/character/',tags:['pirate','healer','transform']},
 {id:'mikasa',name:'Mikasa Ackerman',series:'Attack on Titan',role:'Vanguard',cost:3,color:'#aa98d9',ability:'ODM mobility, blades, close-range cover',forms:['Standard ODM gear','Thunder spears'],endpoint:'Attack on Titan Final Season',sourceLabel:'Attack on Titan official character page',sourceUrl:'https://shingeki.tv/final/character/',tags:['soldier','mobility','melee']},
 {id:'usopp',name:'Usopp',series:'One Piece',role:'Scout',cost:2,color:'#cbb286',ability:'Long-range marksmanship, traps, tactical distraction',forms:['Kabuto','Pop Greens'],endpoint:'Egghead anime arc',sourceLabel:'ONE PIECE.com character directory',sourceUrl:'https://one-piece.com/character/',tags:['pirate','ranged','strategy']},
 {id:'rukia',name:'Rukia Kuchiki',series:'Bleach',role:'Control',cost:4,color:'#8cb6db',ability:'Ice-type Zanpakutō and zone control',forms:['Shikai','Bankai'],endpoint:'Thousand-Year Blood War anime',sourceLabel:'BLEACH official character page',sourceUrl:'https://bleach-anime.com/character/',tags:['sword','ice','spirit']},
 {id:'deku',name:'Izuku Midoriya',series:'My Hero Academia',role:'Vanguard',cost:5,color:'#58b88d',ability:'One For All output, mobility, multiple inherited quirks',forms:['Full Cowling','One For All 100%'],endpoint:'My Hero Academia anime, Final Season',sourceLabel:'My Hero Academia official character page',sourceUrl:'https://heroaca.com/character/',tags:['hero','new-gen','melee']},
 {id:'yuji',name:'Yuji Itadori',series:'Jujutsu Kaisen',role:'Striker',cost:4,color:'#df7896',ability:'Cursed energy reinforcement and close combat',forms:['Cursed energy reinforcement','Black Flash'],endpoint:'Shibuya Incident anime arc',sourceLabel:'Jujutsu Kaisen official character page',sourceUrl:'https://jujutsukaisen.jp/character/',tags:['curse','new-gen','melee']},
 {id:'denji',name:'Denji',series:'Chainsaw Man',role:'Vanguard',cost:4,color:'#db7856',ability:'Hybrid transformation, chainsaws, high endurance',forms:['Human','Chainsaw hybrid'],endpoint:'Chainsaw Man anime season 1',sourceLabel:'Chainsaw Man official character page',sourceUrl:'https://chainsawman.dog/tvseries/character/',tags:['devil','new-gen','transform']},
 {id:'asta',name:'Asta',series:'Black Clover',role:'Control',cost:5,color:'#a9a9bd',ability:'Anti-magic swords and close combat',forms:['Black form','Devil Union'],endpoint:'Black Clover anime, episode 170',sourceLabel:'Black Clover official site',sourceUrl:'https://bclover.jp/',tags:['magic','new-gen','sword']},
 {id:'senku',name:'Senku Ishigami',series:'Dr. Stone',role:'Tactician',cost:2,color:'#9fc86d',ability:'Scientific planning, invention, logistics',forms:['Science Kingdom equipment'],endpoint:'Dr. Stone anime, Science Future',sourceLabel:'Dr. Stone official site',sourceUrl:'https://dr-stone.jp/',tags:['science','new-gen','strategy']},
 {id:'shinra',name:'Shinra Kusakabe',series:'Fire Force',role:'Striker',cost:5,color:'#5f9ed1',ability:'Third-generation ignition and aerial mobility',forms:['Adolla Burst','Rapid'],endpoint:'Fire Force anime season 3',sourceLabel:'Fire Force official site',sourceUrl:'https://fireforce-anime.jp/',tags:['fire','new-gen','mobility']}
];
export const clubs = [
 {id:'jjk',name:'Jujutsu Kaisen',season:'Season 1',episodes:24,color:'#a194ec',letters:'呪',description:'Curses, questions, and episode-by-episode theories.',rules:['Tag the highest episode your post reveals.','No manga material in anime-only threads.','Debate the idea without attacking the fan.']},
 {id:'demon',name:'Demon Slayer',season:'Season 1',episodes:26,color:'#53b8aa',letters:'鬼',description:'Take the journey one episode at a time.',rules:['Use the exact episode tag.','Keep future breathing forms out of earlier threads.','Credit art and translations.']},
 {id:'aot',name:'Attack on Titan',season:'Season 1',episodes:25,color:'#c8a778',letters:'進',description:'Every detail matters. Keep the next reveal a surprise.',rules:['No hints disguised as theories.','Tag the last episode needed for context.','Report accidental future reveals.']}
];
export const starterBattles:Battle[] = [
 {id:'goku-ichigo',fighterAId:'goku',fighterBId:'ichigo',a:'Goku',b:'Ichigo Kurosaki',versionA:'End of Dragon Ball Z',versionB:'End of original Bleach anime',battleType:'knockout',location:'neutral_arena',speed:'equalized',knowledge:'none',prepTime:'none',transformationsAllowed:true,standardEquipment:true,notes:'Neutral empty arena. No preparation. Forms shown by the selected endpoints. Abilities interact across universes.',created:0},
 {id:'naruto-luffy',fighterAId:'naruto',fighterBId:'luffy',a:'Naruto Uzumaki',b:'Monkey D. Luffy',versionA:'End of original Naruto series',versionB:'End of East Blue',battleType:'knockout',location:'neutral_arena',speed:'equalized',knowledge:'none',prepTime:'none',transformationsAllowed:true,standardEquipment:true,notes:'Victory condition: ring out. Circular 100 m arena. No outside assistance. Only abilities shown at these endpoints.',created:0},
 {id:'tanjiro-levi',fighterAId:'tanjiro',fighterBId:'levi',a:'Tanjiro Kamado',b:'Levi Ackerman',versionA:'Season 1',versionB:'Season 1',battleType:'knockout',location:'custom',customLocation:'Abandoned city',speed:'normal',knowledge:'none',prepTime:'none',transformationsAllowed:false,standardEquipment:true,notes:'Starting distance: 30 m. Standard equipment only.',created:0}
];
export const seasonalAnime=[
 {id:'dandadan',title:'Dandadan',genres:['supernatural','comedy','new-gen'],why:'Fast supernatural action with character-driven comedy.'},
 {id:'kaiju8',title:'Kaiju No. 8',genres:['monster','hero','new-gen'],why:'Squad tactics and a protagonist balancing human and monster power.'},
 {id:'frieren',title:'Frieren: Beyond Journey’s End',genres:['fantasy','adventure','strategy'],why:'Quiet character growth, magic systems, and reflective fantasy.'},
 {id:'windbreaker',title:'Wind Breaker',genres:['melee','school','new-gen'],why:'Team loyalty and grounded close-range fights.'},
 {id:'sololeveling',title:'Solo Leveling',genres:['fantasy','power','new-gen'],why:'Clear progression, dungeon battles, and escalating power.'},
 {id:'apothecary',title:'The Apothecary Diaries',genres:['mystery','science','strategy'],why:'Deduction, medicine, and court intrigue.'}
];
export const tournamentSeeds=['tanjiro','deku','denji','yuji','shinra','asta','senku','luffy'];
export function weekKey(){const d=new Date(),first=new Date(Date.UTC(d.getUTCFullYear(),0,1));return `${d.getUTCFullYear()}-W${String(Math.ceil(((+d-+first)/86400000+first.getUTCDay()+1)/7)).padStart(2,'0')}`;}
export function tournamentPhase(){const day=new Date().getUTCDay();return day<=2?'quarterfinals':day<=5?'semifinals':'final';}
export function dailyChallenge(){const day=new Date().toISOString().slice(0,10);const idx=Math.floor(Date.now()/86400000)%3;return {day,boss:['The Iron Colossus','The Phantom Warden','The Storm Titan'][idx],brief:['Break an armored frontline while protecting your support.','Track a mobile opponent and control its escape routes.','Survive ranged pressure and create one decisive opening.'][idx],budget:20,size:5};}
