'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';
import {BookOpen,Check,ChevronRight,Clock3,Library,Rss,Search} from 'lucide-react';
import {toast} from 'sonner';
import {apiFetch} from '@/services/api';

type MediaType='anime'|'manga';
type Tab=MediaType|'watchlist'|'feed';
type MediaItem={id:string;titleCanonical:string;synopsis?:string|null;format?:string|null;releaseYear?:number|null;itemCount?:number|null;genres?:string[];coverImageUrl?:string|null};
type Tracking={mediaType:MediaType;mediaId:string;status:string;currentPosition?:string|null;completedCount:number;title:string;coverImageUrl?:string|null};
type Detail={mediaType:MediaType;row:Record<string,unknown>;episodes?:Array<{id:string;episodeNumber:string;title?:string|null}>;chapters?:Array<{id:string;chapterNumber:string;title?:string|null}>};
type Activity={id:string;handle:string;displayName:string;eventType:string;spoiler?:boolean;createdAt:number};

async function json<T>(url:string,init?:RequestInit):Promise<T>{const r=await apiFetch(url,init),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error((d as {error?:string}).error||'Request failed.');return d as T;}
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export function MediaHub({user,canContribute,initialTab='anime'}:{user:boolean;canContribute:boolean;initialTab?:Tab}){
 const [tab,setTab]=useState<Tab>(initialTab),[query,setQuery]=useState(''),[items,setItems]=useState<MediaItem[]>([]),[tracking,setTrackingState]=useState<Tracking[]>([]),[feed,setFeed]=useState<Activity[]>([]),[detail,setDetail]=useState<Detail|null>(null),[completed,setCompleted]=useState<Set<string>>(new Set()),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 const byMedia=useMemo(()=>new Map(tracking.map(row=>[row.mediaId,row])),[tracking]);
 const loadTracking=useCallback(async()=>{if(!user){setTrackingState([]);return;}try{setTrackingState((await json<{tracking:Tracking[]}>('/api/tracking')).tracking);}catch(e){toast.error((e as Error).message);}},[user]);
 const load=useCallback(async()=>{setLoading(true);try{if(tab==='anime'||tab==='manga'){const p=new URLSearchParams({type:tab,limit:'60'});if(query.trim())p.set('q',query.trim());setItems((await json<{items:MediaItem[]}>('/api/media?'+p)).items);}else if(tab==='watchlist')await loadTracking();else if(user)setFeed((await json<{events:Activity[]}>('/api/social?mode=feed&limit=60')).events);else setFeed([]);}catch(e){toast.error((e as Error).message);}finally{setLoading(false);}},[tab,query,user,loadTracking]);
 useEffect(()=>{void loadTracking();},[loadTracking]);useEffect(()=>{const timer=setTimeout(()=>void load(),query?250:0);return()=>clearTimeout(timer);},[load]);

 async function openMedia(type:MediaType,id:string){setBusy('detail:'+id);try{setDetail(await json<Detail>('/api/media?type='+type+'&id='+encodeURIComponent(id)));if(user){const d=await json<{progress:{completedItemIds:string[]}|null}>('/api/tracking?mode=progress&type='+type+'&mediaId='+encodeURIComponent(id));setCompleted(new Set(d.progress?.completedItemIds||[]));}else setCompleted(new Set());}catch(e){toast.error((e as Error).message);}finally{setBusy('');}}
 async function track(type:MediaType,mediaId:string,status:string){if(!canContribute){toast.error('Complete account verification before saving progress.');return;}setBusy('track:'+mediaId);try{await json('/api/tracking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'set_tracking',mediaType:type,mediaId,status,currentPosition:null,activityVisibility:'private'})});toast.success('Tracking updated.');await loadTracking();}catch(e){toast.error((e as Error).message);}finally{setBusy('');}}
 async function toggle(type:MediaType,itemId:string,done:boolean){if(!canContribute)return;const action=type==='anime'?(done?'uncomplete_episode':'complete_episode'):(done?'uncomplete_chapter':'complete_chapter'),field=type==='anime'?'episodeId':'chapterId';setBusy('item:'+itemId);try{await json('/api/tracking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,[field]:itemId})});setCompleted(current=>{const next=new Set(current);done?next.delete(itemId):next.add(itemId);return next;});await loadTracking();}catch(e){toast.error((e as Error).message);}finally{setBusy('');}}

 return <div className="ac-community media-hub">
  <div className="ac-heading"><div><span className="ac-eyebrow">TRACK WHAT YOU ACTUALLY WATCH</span><h1>Anime &amp; manga library</h1><p>Canonical catalogue, personal progress, and a privacy-safe following feed.</p></div><span className="ac-heading-icon"><Library size={24}/></span></div>
  <div className="media-tabs">{([['anime','Anime',Library],['manga','Manga',BookOpen],['watchlist','My list',Clock3],['feed','Following',Rss]] as const).map(([id,name,Icon])=><button type="button" key={id} className={tab===id?'is-active':''} onClick={()=>{setTab(id);setDetail(null);}}><Icon size={16}/>{name}</button>)}</div>
  {(tab==='anime'||tab==='manga')&&<label className="ac-search media-search"><Search size={17}/><input aria-label="Search catalogue" value={query} onChange={e=>setQuery(e.target.value)} placeholder={'Search '+tab}/></label>}
  {loading&&<div className="ac-empty">Loading {tab}...</div>}
  {!loading&&(tab==='anime'||tab==='manga')&&<div className="media-grid">{items.map(item=>{const current=byMedia.get(item.id);return <article className="ac-surface media-card" key={item.id}>{item.coverImageUrl?<img src={item.coverImageUrl} alt="" referrerPolicy="no-referrer"/>:<div className="media-cover-fallback">{item.titleCanonical[0]}</div>}<div><span className="ac-eyebrow">{item.format||tab}</span><h2>{item.titleCanonical}</h2><p>{item.synopsis||'Metadata is still being curated.'}</p><div className="ac-tag-row">{(item.genres||[]).slice(0,4).map(g=><span key={g}>{g}</span>)}</div><small>{item.releaseYear||'Year unknown'} · {item.itemCount??'?'} {tab==='anime'?'episodes':'chapters'} · {current?label(current.status):'Not tracked'}</small><div className="media-actions"><button className="ac-button-subtle" type="button" disabled={busy==='detail:'+item.id} onClick={()=>void openMedia(tab,item.id)}>Details <ChevronRight size={14}/></button>{user&&<select className="ac-select compact" value={current?.status||'planned'} disabled={!canContribute||busy==='track:'+item.id} onChange={e=>void track(tab,item.id,e.target.value)} aria-label={'Tracking status for '+item.titleCanonical}><option value="planned">Plan</option><option value={tab==='anime'?'watching':'reading'}>{tab==='anime'?'Watching':'Reading'}</option><option value="completed">Completed</option><option value="paused">Paused</option><option value="dropped">Dropped</option><option value={tab==='anime'?'rewatching':'rereading'}>{tab==='anime'?'Rewatching':'Rereading'}</option></select>}</div></div></article>})}{!items.length&&<div className="ac-empty">No results.</div>}</div>}
  {!loading&&tab==='watchlist'&&(!user?<div className="ac-empty">Sign in to keep a personal list.</div>:<div className="media-grid">{tracking.map(row=><article className="ac-surface media-card compact-card" key={row.mediaType+row.mediaId}>{row.coverImageUrl?<img src={row.coverImageUrl} alt="" referrerPolicy="no-referrer"/>:<div className="media-cover-fallback">{row.title[0]}</div>}<div><span className="ac-eyebrow">{row.mediaType}</span><h2>{row.title}</h2><p>{label(row.status)} · {row.completedCount} completed{row.currentPosition?' · position '+row.currentPosition:''}</p><button className="ac-button-subtle" type="button" onClick={()=>void openMedia(row.mediaType,row.mediaId)}>Update progress <ChevronRight size={14}/></button></div></article>)}</div>)}
  {!loading&&tab==='feed'&&(!user?<div className="ac-empty">Sign in to see followed activity.</div>:<section className="ac-surface media-feed"><span className="ac-eyebrow">FOLLOWING FEED</span><h2>Recent activity</h2>{feed.length?feed.map(event=><article className="media-feed-row" key={event.id}><div><strong>{event.displayName}</strong> <small>@{event.handle}</small><p>{event.spoiler?'Spoiler-sensitive activity hidden for your progress.':label(event.eventType)}</p></div><time>{new Date(event.createdAt).toLocaleString()}</time></article>):<div className="ac-empty">Follow public profiles to build your feed.</div>}</section>)}
  {detail&&<section className="ac-surface media-detail"><div className="media-detail-head"><div><span className="ac-eyebrow">{detail.mediaType} DETAILS</span><h2>{String(detail.row.title_canonical||'Untitled')}</h2></div><button type="button" className="ac-button-subtle" onClick={()=>setDetail(null)}>Close</button></div><p>{String(detail.row.synopsis||'No synopsis synchronized yet.')}</p>{detail.mediaType==='anime'?<ItemList title="Episodes" empty="Episode-level metadata has not been synchronized. No placeholder episodes were fabricated." rows={(detail.episodes||[]).map(x=>({id:x.id,label:'Episode '+x.episodeNumber,title:x.title}))} completed={completed} busy={busy} disabled={!canContribute} toggle={(id,done)=>toggle('anime',id,done)}/>:<ItemList title="Chapters" empty="Chapter-level metadata has not been synchronized. No fictional chapter catalogue was created." rows={(detail.chapters||[]).map(x=>({id:x.id,label:'Chapter '+x.chapterNumber,title:x.title}))} completed={completed} busy={busy} disabled={!canContribute} toggle={(id,done)=>toggle('manga',id,done)}/>}</section>}
 </div>;
}

function ItemList({title,empty,rows,completed,busy,disabled,toggle}:{title:string;empty:string;rows:{id:string;label:string;title?:string|null}[];completed:Set<string>;busy:string;disabled:boolean;toggle:(id:string,done:boolean)=>void}){
 return <div className="media-item-list"><h3>{title}</h3>{rows.length?rows.map(row=>{const done=completed.has(row.id);return <button type="button" key={row.id} disabled={disabled||busy==='item:'+row.id} className={done?'is-complete':''} onClick={()=>toggle(row.id,done)}><span>{done?<Check size={15}/>:<span className="media-check"/>} {row.label}</span><small>{row.title||'Title unavailable'}</small></button>}):<div className="ac-empty">{empty}</div>}</div>;
}
