"""Generate a PostgreSQL starting schema from the fully migrated D1 schema.

The historical SQLite migrations are executed only in an in-memory SQLite
database. Their final shape is inspected; their SQL is never sent to Postgres.
Run from the repository root. Review the generated SQL before applying it.
"""

import glob
import pathlib
import sqlite3

root = pathlib.Path(__file__).resolve().parents[2]
db = sqlite3.connect(":memory:")
db.execute("PRAGMA foreign_keys=ON")
for migration in sorted(glob.glob(str(root / "drizzle" / "[0-9]*.sql"))):
    for statement in pathlib.Path(migration).read_text().split("--> statement-breakpoint"):
        if statement.strip():
            db.executescript(statement)

tables = [row[0] for row in db.execute(
    "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
)]
out = ["-- Anime Clash PostgreSQL baseline from D1 migrations 0000..0010.",
       "-- Apply only to an empty database. Historical IDs and millisecond timestamps remain unchanged."]
for table in tables:
    columns = db.execute(f'PRAGMA table_info("{table}")').fetchall()
    keys = [r[1] for r in sorted(columns, key=lambda r: r[5]) if r[5]]
    declarations = []
    for _, name, kind, required, default, _ in columns:
        pg_kind = "BIGINT" if kind.upper() == "INTEGER" else "TEXT"
        line = f'"{name}" {pg_kind}'
        if required:
            line += " NOT NULL"
        if default is not None:
            line += f" DEFAULT {default}"
        declarations.append(line)
    if table == "votes":
        # SQLite's hidden rowid was exposed as an argument ID in the API.
        declarations.append('"argument_id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE')
    if keys:
        declarations.append("PRIMARY KEY (" + ", ".join(f'"{key}"' for key in keys) + ")")
    for fk in db.execute(f'PRAGMA foreign_key_list("{table}")'):
        declarations.append(f'FOREIGN KEY ("{fk[3]}") REFERENCES "{fk[2]}" ("{fk[4]}") ON DELETE {fk[6]}')
    if table == "version_combat_roles":
        declarations += [
            "CHECK (role IN ('dps','tank','support','healer','controller','strategist','assassin','speedster','summoner','reality_manipulator','defense'))",
            "CHECK (priority IN ('primary','secondary'))",
        ]
    if table == "version_strategic_traits":
        declarations.append("CHECK (trait IN ('healing','barrier','crowd_control','mobility','teleportation','information','buff','debuff','sealing','summoning','illusion','stealth','long_range','close_range','area_damage','single_target','adaptation','prediction','anti_regeneration'))")
    out.append(f'CREATE TABLE "{table}" (\n  ' + ",\n  ".join(declarations) + "\n);")

for name, statement in db.execute("SELECT name,sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name"):
    # All named SQLite indexes in this project are standard PostgreSQL syntax
    # after identifier quotation changes. There are no expression indexes.
    out.append(statement.replace("`", '"') + ";")

destination = root / "docs/migration/d1-schema-derivation.sql"
destination.parent.mkdir(parents=True, exist_ok=True)
destination.write_text("\n\n".join(out) + "\n")
print(f"Wrote {destination.relative_to(root)} with {len(tables)} tables")
