'use client';

import {useState, type Dispatch, type SetStateAction, type ReactNode} from 'react';
import {ArrowRight, Check, Copy, Edit3, Flag, Lock, MessageCircle, Search, ShieldCheck, Trash2, Users, X} from 'lucide-react';
import {clubs, fighters} from '@anime/domain/catalog';
import {ProfileSocialPanel} from '@/components/profile-social-panel';

type Save = (payload: Record<string, unknown>, success?: string) => Promise<unknown | null>;
type Reload = () => Promise<void> | void;
type Club = (typeof clubs)[number];
type Post = {id:string;handle:string;displayName:string;episode:number;body:string;owned:boolean;edited?:boolean;created?:number};
type ClubData = {episode:number;locked:number;posts:Post[];rules?:string[]};
type Fan = {handle:string;displayName:string;avatarUrl?:string|null;favoriteAnime:string[];favoriteCharacters:string[];match?:number|null};
type Anime = {id:string;title:string;genres:string[];why:string};
type WatchStatus = 'remove' | 'planned' | 'watching' | 'completed';
type DiscoverData = {profiles:Fan[];recommendations:Anime[];watchlist:{anime:string;status:WatchStatus}[]};
export type CommunityProfile = {handle:string;displayName:string;avatarUrl?:string|null;bio:string;favoriteAnime:string[];favoriteCharacters:string[];created?:number;owned?:boolean};
export type ProfileDraft = {handle:string;displayName:string;avatarUrl:string;bio:string;favoriteAnime:string[];favoriteCharacters:string[]};
type Squad = {id:string;name:string;members:string[];strategy:string};
type ChallengeEntry = {id:string;challengeTitle:string;name:string;totalCost:number;budget:number;totalVotes:number};
export type ProfileResponse = {profile:CommunityProfile|null;record?:{total:number};squads?:Squad[];challengeSubmissions?:ChallengeEntry[];progress?:{club:string;episode:number}[]};

function SectionHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){
 return <div className="ac-heading"><div><span className="ac-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>;
}
function Avatar({name,src}:{name:string;src?:string|null}){
 return <span className="ac-avatar">{src?<img src={src} alt="" referrerPolicy="no-referrer"/>:<span aria-hidden="true">{name.slice(0,2).toUpperCase()}</span>}</span>;
}
function Notice({children}:{children:ReactNode}){return <div className="ac-empty" role="status">{children}</div>;}
function SelectEpisode({value,onChange,limit,label}:{value:string;onChange:(value:string)=>void;limit:number;label:string}){
 return <label className="ac-field ac-select-field"><span>{label}</span><select className="ac-select" value={value} onChange={e=>onChange(e.target.value)}>{Array.from({length:Math.max(0,limit)+1},(_,i)=><option key={i} value={String(i)}>Episode {i}</option>)}</select></label>;
}
function Discussion({post,onSave,onReload,onReport,onOpenProfile,busy}:{post:Post;onSave:Save;onReload:Reload;onReport:(type:string,id:string)=>Promise<void>;onOpenProfile:(handle:string)=>void;busy:boolean}){
 const [editing,setEditing]=useState(false),[text,setText]=useState(post.body),[working,setWorking]=useState(false);
 const valid=text.trim().length>=5&&text.trim().length<=2000;
 async function update(){setWorking(true);try{if(await onSave({action:'edit_post',post:post.id,body:text},'Post updated.')){setEditing(false);await onReload();}}finally{setWorking(false);}}
 async function remove(){if(!window.confirm('Delete this discussion?'))return;setWorking(true);try{if(await onSave({action:'delete_post',post:post.id},'Discussion deleted.'))await onReload();}finally{setWorking(false);}}
 return <article className="ac-post"><div className="ac-post-top"><Avatar name={post.displayName}/><div className="ac-post-author"><strong>{post.displayName}</strong><button type="button" className="ac-text-button" onClick={()=>onOpenProfile(post.handle)}>@{post.handle}</button></div><span className="ac-pill">Episode {post.episode}</span>{post.created? <time dateTime={new Date(post.created).toISOString()}>{new Date(post.created).toLocaleDateString()}</time>:null}{post.edited&&<small>Edited</small>}</div>
 {editing?<div className="ac-edit-post"><label htmlFor={'edit-'+post.id}>Edit discussion</label><textarea id={'edit-'+post.id} maxLength={2000} rows={4} value={text} onChange={e=>setText(e.target.value)}/><div className="ac-inline-actions"><span>{text.length}/2000</span><button type="button" className="ac-button-subtle" onClick={()=>{setEditing(false);setText(post.body);}} disabled={working}>Cancel</button><button type="button" className="ac-button" onClick={()=>void update()} disabled={busy||working||!valid}>Save changes</button></div></div>:<p className="ac-post-body">{post.body}</p>}
 <div className="ac-post-actions">{post.owned&&!editing&&<button type="button" onClick={()=>{setText(post.body);setEditing(true);}} disabled={working||busy}><Edit3 size={15}/> Edit</button>}{post.owned&&!editing&&<button type="button" onClick={()=>void remove()} disabled={working||busy}><Trash2 size={15}/> Delete</button>}<button type="button" onClick={()=>void onReport('post',post.id)} disabled={working||busy}><Flag size={15}/> Report</button></div></article>;
}
export function Clubs({club,clubId,setClubId,data,episode,setEpisode,postEpisode,setPostEpisode,body,setBody,busy,save,reload,report,openProfile,canContribute,error,loading}:{club:Club;clubId:string;setClubId:(id:string)=>void;data:ClubData|null;episode:string;setEpisode:(value:string)=>void;postEpisode:string;setPostEpisode:(value:string)=>void;body:string;setBody:(value:string)=>void;busy:boolean;save:Save;reload:Reload;report:(type:string,id:string)=>Promise<void>;openProfile:(handle:string)=>void;canContribute:boolean;error?:string;loading?:boolean}){
 const [search,setSearch]=useState('');
 const saved=Math.max(0,Math.min(club.episodes,data?.episode??0));
 const validPost=body.trim().length>=5&&body.trim().length<=2000;
 return <div className="ac-community"><SectionHeading eyebrow="THE WATCH PARTY" title="Anime Clubs" description="Discuss the episodes you have actually seen. Plot twists stay behind your spoiler shield." action={<span className="ac-heading-icon"><Users size={24}/></span>}/>
 <div className="ac-selector-title"><h2>Choose your community</h2><label className="ac-search"><Search size={17}/><span className="sr-only">Search anime clubs</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a club..."/></label></div>
 <div className="ac-club-grid">{clubs.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())).map(c=><button type="button" key={c.id} className={'ac-club-card'+(clubId===c.id?' is-current':'')} aria-pressed={clubId===c.id} onClick={()=>setClubId(c.id)}><span className="ac-club-logo" style={{color:c.color}}>{c.letters}</span><span className="ac-club-text"><strong>{c.name}</strong><small>{c.season} · {c.episodes} episodes</small></span>{clubId===c.id?<Check size={18} aria-hidden="true"/>:<ArrowRight size={16} aria-hidden="true"/>}</button>)}{!clubs.some(c=>c.name.toLowerCase().includes(search.toLowerCase()))&&<Notice>No clubs match that search.</Notice>}</div>
 <div className="ac-community-grid"><section className="ac-surface ac-feed"><div className="ac-feed-intro"><span className="ac-eyebrow">CLUB DISCUSSIONS</span><h2>{club.name}</h2><p>{club.description}</p><span className="ac-safe-status"><ShieldCheck size={15}/> Safe through episode {saved}</span></div>
 {!data?<Notice>{error&&!loading?'Could not load discussions. Use the Retry action above.':'Loading your spoiler-safe discussions...'}</Notice>:<>{!canContribute&&<Notice>Sign in, verify your email and complete your profile to post or save progress.</Notice>}<form className="ac-composer" onSubmit={async e=>{e.preventDefault();if(!canContribute||!validPost||Number(postEpisode)>saved)return;if(await save({action:'post',club:clubId,episode:Number(postEpisode),body:body.trim()},'Discussion posted.')){setBody('');await reload();}}}><label htmlFor="ac-discussion-body">Start a conversation</label><textarea id="ac-discussion-body" rows={4} maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder="What did you notice? What theory are you following?"/><div className="ac-composer-foot"><SelectEpisode value={postEpisode} onChange={setPostEpisode} limit={saved} label="Episode tag"/><span className="ac-character-count">{body.length}/2000</span><button className="ac-button" type="submit" disabled={!canContribute||busy||!validPost||Number(postEpisode)>saved}>Post discussion <ArrowRight size={16}/></button></div></form>
 <div className="ac-feed-label"><h3>Latest discussions</h3><span>{data.posts.length} visible</span></div>{data.posts.length?data.posts.map(p=><Discussion key={p.id} post={p} onSave={save} onReload={reload} onReport={report} onOpenProfile={openProfile} busy={busy}/>):<Notice><MessageCircle size={21}/> No discussions within your watched episodes yet. Start one above.</Notice>}{data.locked>0&&<div className="ac-locked"><Lock size={17}/><span>{data.locked} later-episode discussion{data.locked===1?' is':'s are'} hidden to protect your progress.</span></div>}</>}</section>
 <aside className="ac-community-aside"><section className="ac-surface ac-shield"><span className="ac-shield-icon"><ShieldCheck size={25}/></span><span className="ac-eyebrow">SPOILER PROTECTION</span><h2>Your spoiler shield</h2><p>Only discussions at or before your saved episode are returned by the server.</p><div className="ac-progress-current">Saved progress <strong>Episode {saved} of {club.episodes}</strong></div><SelectEpisode value={episode} onChange={setEpisode} limit={club.episodes} label="Last completed episode"/><button className="ac-button ac-wide" type="button" disabled={!canContribute||busy||!data||Number(episode)===saved} onClick={async()=>{if(canContribute&&await save({action:'progress',club:clubId,episode:Number(episode)},'Viewing progress saved.'))await reload();}}>Save progress</button><div className="ac-rules"><h3>Club rules</h3>{(data?.rules||club.rules).map(rule=><p key={rule}><Check size={14}/>{rule}</p>)}</div></section></aside></div></div>;
}
const statusChoices:{value:WatchStatus;label:string}[]=[{value:'remove',label:'Not saved'},{value:'planned',label:'Plan to watch'},{value:'watching',label:'Watching'},{value:'completed',label:'Completed'}];
function WatchlistCard({anime,status,save,reload,disabled}:{anime:Anime;status:WatchStatus;save:Save;reload:Reload;disabled:boolean}){
 const [working,setWorking]=useState(false);
 async function update(next:WatchStatus){if(working||next===status)return;setWorking(true);try{if(await save({action:'watchlist',anime:anime.id,status:next},'Watchlist updated.'))await reload();}finally{setWorking(false);}}
 return <article className="ac-surface ac-anime-card"><span className="ac-anime-symbol" aria-hidden="true">{anime.title.slice(0,1)}</span><div className="ac-anime-info"><span className="ac-eyebrow">ANIME PICK</span><h3>{anime.title}</h3><div className="ac-tag-row">{anime.genres.map(g=><span key={g}>{g}</span>)}</div><p>{anime.why}</p><label className="ac-field"><span>Watchlist status {disabled?<span>· Sign in to save</span>:working&&<span role="status">· Saving...</span>}</span><select className="ac-select" value={status} onChange={e=>void update(e.target.value as WatchStatus)} disabled={working||disabled}>{statusChoices.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div></article>;
}
export function Discover({data,save,reload,openProfile,current,user,error,loading}:{data:DiscoverData|null;save:Save;reload:Reload;openProfile:(handle:string)=>void;current:CommunityProfile|null;user:boolean;error?:string;loading?:boolean}){
 const [fanQuery,setFanQuery]=useState(''),[animeQuery,setAnimeQuery]=useState(''),[genre,setGenre]=useState('all');
 const fans=(data?.profiles??[]).filter(p=>(p.displayName+' '+p.handle+' '+p.favoriteAnime.join(' ')).toLowerCase().includes(fanQuery.toLowerCase()));
 const genres=[...new Set((data?.recommendations??[]).flatMap(a=>a.genres))].sort();
 const anime=(data?.recommendations??[]).filter(a=>(genre==='all'||a.genres.includes(genre))&&a.title.toLowerCase().includes(animeQuery.toLowerCase()));
 return <div className="ac-community"><SectionHeading eyebrow="FIND YOUR PEOPLE" title="Discover" description="Meet fans who share your interests and find a new series for your watchlist."/>
 <div className="ac-discover-grid"><section className="ac-discover-people"><div className="ac-block-heading"><div><span className="ac-eyebrow">COMMUNITY</span><h2>Discover fans</h2><p>Explore public profiles and their favourite anime.</p></div><label className="ac-search"><Search size={17}/><span className="sr-only">Search fans</span><input value={fanQuery} onChange={e=>setFanQuery(e.target.value)} placeholder="Search fans"/></label></div>
 {!data?<Notice>{error&&!loading?'Could not load fans. Use Retry above.':'Loading fan profiles...'}</Notice>:<div className="ac-fans">{fans.map(p=><button type="button" className="ac-surface ac-fan" onClick={()=>openProfile(p.handle)} key={p.handle}><div className="ac-fan-top"><Avatar name={p.displayName} src={p.avatarUrl}/><div><h3>{p.displayName}</h3><span>@{p.handle}</span></div><ArrowRight size={17}/></div><div className="ac-fan-interests">{p.favoriteAnime.slice(0,3).map(x=><span key={x}>{x}</span>)}{p.favoriteAnime.length===0&&<small>Still building their anime list</small>}</div>{p.match!=null&&current&&[...p.favoriteAnime.filter(x=>current.favoriteAnime.includes(x)),...p.favoriteCharacters.filter(x=>current.favoriteCharacters.includes(x))].length>0&&<div className="ac-fan-match"><Check size={14}/>{p.match}% taste match</div>}</button>)}{!fans.length&&<Notice>{fanQuery?'No public profiles match your search.':'No public profiles to discover yet.'}</Notice>}</div>}</section>
 <section className="ac-discover-anime"><div className="ac-block-heading"><div><span className="ac-eyebrow">THE NEXT EPISODE</span><h2>Recommended anime</h2><p>Suggestions based on your interests where available.</p></div></div><div className="ac-recommend-filters"><label className="ac-search"><Search size={17}/><span className="sr-only">Search anime</span><input value={animeQuery} onChange={e=>setAnimeQuery(e.target.value)} placeholder="Search anime"/></label><label className="sr-only" htmlFor="ac-genre">Filter genres</label><select id="ac-genre" className="ac-select" value={genre} onChange={e=>setGenre(e.target.value)}><option value="all">All genres</option>{genres.map(g=><option key={g} value={g}>{g}</option>)}</select></div>
 {!data?<Notice>{error&&!loading?'Could not load recommendations. Use Retry above.':'Loading recommendations...'}</Notice>:<div className="ac-anime-list">{anime.map(a=><WatchlistCard key={a.id} anime={a} status={data.watchlist.find(w=>w.anime===a.id)?.status||'remove'} save={save} reload={reload} disabled={!user}/>)}{!anime.length&&<Notice>No anime found for these filters.</Notice>}</div>}</section></div></div>;
}
function FanFavorites({values,characters=false}:{values:string[];characters?:boolean}){
 return <div className="ac-favorites">{values.length?values.map(id=><span key={id}>{characters?fighters.find(f=>f.id===id)?.name||id:id}</span>):<span className="ac-missing">Nothing added yet</span>}</div>;
}
export function ProfilePage({user,current,page,draft,setDraft,busy,signIn,saveProfile,share,requestedHandle,loading}:{user:boolean;current:CommunityProfile|null;page:ProfileResponse|null;draft:ProfileDraft;setDraft:Dispatch<SetStateAction<ProfileDraft>>;busy:boolean;signIn:()=>void;saveProfile:()=>Promise<boolean>;share:(type:string,id:string)=>Promise<void>;requestedHandle:string;loading:boolean}){
 const [editing,setEditing]=useState(false);
 const p=requestedHandle?page?.profile:(page?.profile||current);
 const owned=Boolean(user&&p&&(requestedHandle?p.owned:true));
 const reset=()=>{if(current){const original={handle:current.handle,displayName:current.displayName,avatarUrl:current.avatarUrl||'',bio:current.bio,favoriteAnime:[...current.favoriteAnime],favoriteCharacters:[...current.favoriteCharacters]};if(JSON.stringify(draft)!==JSON.stringify(original)&&!window.confirm('Discard unsaved profile changes?'))return;setDraft(original);}setEditing(false);};
 if(loading)return <div className="ac-community"><Notice>Loading fan profile...</Notice></div>;
 if(requestedHandle&&!p)return <div className="ac-community"><SectionHeading eyebrow="FAN PROFILE" title="Profile unavailable" description="This public profile does not exist or is not available."/><Notice>Check the profile link or return to Discover.</Notice></div>;
 if(!requestedHandle&&!user)return <div className="ac-community"><SectionHeading eyebrow="YOUR ANIME IDENTITY" title="Create your fan profile" description="Sign in to save your favourites, squads, and community activity."/><button className="ac-button" onClick={signIn}>Sign in <ArrowRight size={17}/></button></div>;
 if(!p)return <div className="ac-community"><SectionHeading eyebrow="YOUR ANIME IDENTITY" title="Set up your profile" description="Let the community know which stories and characters you love."/><ProfileForm draft={draft} setDraft={setDraft} busy={busy} saveProfile={saveProfile}/></div>;
 const squads=page?.squads??[],history=page?.challengeSubmissions??[];
 return <div className="ac-community"><SectionHeading eyebrow="FAN IDENTITY" title="Fan profile" description="Favourites, community contributions, and the squads behind the strategy." action={<div className="ac-profile-actions"><button className="ac-button-subtle" type="button" onClick={()=>void share('profile',p.handle)}><Copy size={15}/> Share profile</button>{owned&&!editing&&<button className="ac-button" type="button" onClick={()=>setEditing(true)}><Edit3 size={15}/> Edit profile</button>}</div>}/>
 <div className="ac-profile-cover ac-surface"><span className="ac-profile-glow" aria-hidden="true"/><Avatar name={p.displayName} src={p.avatarUrl}/><div className="ac-profile-identity"><h2>{p.displayName}</h2><span>@{p.handle}</span><p>{p.bio||'This fan has not added a biography yet.'}</p>{p.created&&<small>Member since {new Date(p.created).toLocaleDateString()}</small>}</div></div>
 {editing&&owned&&<ProfileForm draft={draft} setDraft={setDraft} busy={busy} saveProfile={async()=>{if(await saveProfile())setEditing(false);}} onCancel={reset} compact/>}
 <div className="ac-profile-stat-grid"><div className="ac-surface"><strong>{page?.record?.total??0}</strong><span>Battle votes</span></div><div className="ac-surface"><strong>{squads.length}</strong><span>Recent squads</span></div><div className="ac-surface"><strong>{history.length}</strong><span>Recent challenge entries</span></div><div className="ac-surface"><strong>{page?.progress?.length??0}</strong><span>Active clubs</span></div></div>
 <div className="ac-profile-sections"><section className="ac-surface"><span className="ac-eyebrow">THE WATCHLIST</span><h2>Favourite anime</h2><FanFavorites values={p.favoriteAnime}/><h2>Favourite characters</h2><FanFavorites values={p.favoriteCharacters} characters/></section><section className="ac-surface"><span className="ac-eyebrow">TEAM STRATEGY</span><h2>Saved squads</h2>{squads.length?squads.map(s=><div className="ac-history" key={s.id}><strong>{s.name}</strong><p>{s.members.map(id=>fighters.find(f=>f.id===id)?.name||id).join(' · ')}</p><small>{s.strategy}</small></div>):<Notice>No saved squads yet.</Notice>}</section></div>
 <section className="ac-surface ac-history-panel"><span className="ac-eyebrow">COMPETITIVE HISTORY</span><h2>Squad challenge entries</h2>{history.length?history.map(e=><div className="ac-history ac-history-share" key={e.id}><div><small>{e.challengeTitle}</small><strong>{e.name}</strong><p>{e.totalCost} / {e.budget} points · {e.totalVotes} votes</p></div><button className="ac-button-subtle" type="button" onClick={()=>void share('challengeSquad',e.id)}><Copy size={14}/> Share</button></div>):<Notice>No challenge entries yet.</Notice>}</section>
 <ProfileSocialPanel handle={p.handle} user={user}/>
 </div>;
}
const animeOptions=['Dragon Ball','Bleach','Naruto','One Piece','Demon Slayer','Attack on Titan','Jujutsu Kaisen','My Hero Academia','Chainsaw Man','Black Clover','One-Punch Man'];
export function ProfileForm({draft,setDraft,busy,saveProfile,onCancel,compact=false}:{draft:ProfileDraft;setDraft:Dispatch<SetStateAction<ProfileDraft>>;busy:boolean;saveProfile:()=>Promise<boolean|void>;onCancel?:()=>void;compact?:boolean}){
 const [characterSearch,setCharacterSearch]=useState('');
 const [animeSearch,setAnimeSearch]=useState('');
 const availableAnime=[...new Set([...animeOptions,...fighters.map(f=>f.series),...draft.favoriteAnime])].sort((a,b)=>a.localeCompare(b));
 const toggle=(key:'favoriteAnime'|'favoriteCharacters',value:string)=>setDraft(d=>({...d,[key]:d[key].includes(value)?d[key].filter(x=>x!==value):d[key].length<8?[...d[key],value]:d[key]}));
 const valid=draft.handle.length>=3&&draft.handle.length<=24&&Boolean(draft.displayName.trim())&&draft.displayName.length<=120&&draft.bio.length<=400;
 return <form className={'ac-surface ac-profile-editor'+(compact?' is-compact':'')} onSubmit={e=>{e.preventDefault();if(valid&&!busy)void saveProfile();}}><div className="ac-edit-head"><div><span className="ac-eyebrow">MAKE IT YOURS</span><h2>{compact?'Edit your profile':'Build your public profile'}</h2></div>{onCancel&&<button type="button" className="ac-icon-button" aria-label="Cancel profile editing" onClick={onCancel}><X size={19}/></button>}</div>
 <div className="ac-form-row"><label className="ac-field">Handle <input required minLength={3} maxLength={24} pattern="[a-z0-9_]{3,24}" value={draft.handle} onChange={e=>setDraft(d=>({...d,handle:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,'')}))} placeholder="anime_handle"/><small>3 to 24 lowercase letters, digits or underscores</small></label><label className="ac-field">Display name <input required maxLength={120} value={draft.displayName} onChange={e=>setDraft(d=>({...d,displayName:e.target.value}))} placeholder="How other fans know you"/></label></div>
 <label className="ac-field">Avatar URL <small>Optional, HTTPS only</small><input type="url" maxLength={1000} pattern="https://.*" value={draft.avatarUrl||''} onChange={e=>setDraft(d=>({...d,avatarUrl:e.target.value}))} placeholder="https://example.com/avatar.png"/></label>
 <label className="ac-field">Biography <span className="ac-field-count">{draft.bio.length}/400</span><textarea maxLength={400} rows={3} value={draft.bio} onChange={e=>setDraft(d=>({...d,bio:e.target.value}))} placeholder="Your favourite genres, battle style, and current watchlist"/></label>
 <div className="ac-favorite-editor"><div className="ac-option-heading"><h3>Favourite anime</h3><span>{draft.favoriteAnime.length}/8 selected</span></div><label className="ac-search"><Search size={16}/><span className="sr-only">Search favourite anime</span><input value={animeSearch} onChange={e=>setAnimeSearch(e.target.value)} placeholder="Filter anime"/></label><div className="ac-options">{availableAnime.filter(x=>x.toLowerCase().includes(animeSearch.toLowerCase())).map(x=><button key={x} type="button" aria-pressed={draft.favoriteAnime.includes(x)} className={draft.favoriteAnime.includes(x)?'is-selected':''} onClick={()=>toggle('favoriteAnime',x)}>{x}{draft.favoriteAnime.includes(x)&&<Check size={13}/>}</button>)}</div></div>
 <div className="ac-favorite-editor"><div className="ac-option-heading"><h3>Favourite characters</h3><span>{draft.favoriteCharacters.length}/8 selected</span></div><label className="ac-search"><Search size={16}/><span className="sr-only">Search favourite characters</span><input value={characterSearch} onChange={e=>setCharacterSearch(e.target.value)} placeholder="Search all characters"/></label><div className="ac-options ac-character-options">{fighters.filter(f=>f.name.toLowerCase().includes(characterSearch.toLowerCase())||f.series.toLowerCase().includes(characterSearch.toLowerCase())).map(f=><button key={f.id} type="button" aria-pressed={draft.favoriteCharacters.includes(f.id)} className={draft.favoriteCharacters.includes(f.id)?'is-selected':''} onClick={()=>toggle('favoriteCharacters',f.id)}>{f.name}<small>{f.series}</small>{draft.favoriteCharacters.includes(f.id)&&<Check size={13}/>}</button>)}</div></div>
 <div className="ac-form-actions">{onCancel&&<button type="button" className="ac-button-subtle" onClick={onCancel} disabled={busy}>Cancel</button>}<button type="submit" className="ac-button" disabled={busy||!valid}>{busy?'Saving...':'Save profile'}<Check size={16}/></button></div></form>;
}
